### ISSUE TITLE
Publicarlo como paquete de Composer

### ISSUE THREAD

**Issue by PhoneixS** [josemmo/Facturae-PHP#1]
Seguramente sería buena idea publicar la clase como un paquete de composer (https://getcomposer.org/) para facilitar su uso y distribución ya que es la forma más común de publicar librerías para php.

**Comment by PhoneixS** [comment]
Se que tener un solo archivo con todo parece con conveniente a primera vista pero realmente sería buena idea (además de casi necesario para crear el paquete de Composer) que estuviera cada clase en su propio archivo.

Básicamente habría que hacer los siguientes cambios para resolver adecuadamente esta incidencia:
 - Organizar el código fuente. Por ejemplo poner el código fuente en una carpeta llamada src.
 - Establecer un espacio de nombres.
 - Separar las clases en archivos individuales.
 - Agregar el package.json correspondiente al proyecto configurando el autoload para la carpeta src y el namespace correspondiente.
 - Finalmente publicarlo e packagist.

**Comment by josemmo** [comment]
Me parece muy buena idea, @PhoneixS. A ver si puedo sacar tiempo para adaptarlo cuanto antes.

Si alguien se ve con ganas acepto pull requests encantado.

**Comment by PhoneixS** [comment]
Hay tienes la conversión inicial, queda que lo retoques con los datos correctos en el composer.json y publicarlo a packagist.

**Comment by josemmo** [comment]
Ya está publicado en Packagist: https://packagist.org/packages/josemmo/facturae-php
