### ISSUE TITLE
Varios vencimientos

### ISSUE THREAD

**Issue by FerCapFor1966** [josemmo/Facturae-PHP#100]
Te agradezco el magnifico trabajo que estas realizando.
Es posible incluir más de un vencimiento por factura ?
Si modifico manualmente al XML generado y le incluyo otro nodo de la clase 'Installment' con los datos de otro vencimiento y lo importo con la aplicación Factura-e del ministerio de hacienda, se visualizan los dos vencimientos con sus correspondientes fechas e importes.
Grácias

**Comment by josemmo** [comment]
Hola @FerCapFor1966,

Acabo de añadir esta funcionalidad a través del método `Facturae::addPayment()`, que sustituirá a `Facturae::setPaymentMethod()`.

Puedes probar los cambios desde la rama "develop":
```
composer require josemmo/facturae-php:dev-develop
```

Tienes la nueva documentación en [este enlace](https://github.com/josemmo/Facturae-PHP/blob/develop/doc/propiedades/datos-del-pago.md).

**Comment by FerCapFor1966** [comment]
Muchas grácias !! funciona perfectamente.
