### ISSUE TITLE
OpenSSL 3.0.x no reconoce ciertos certificados digitales p12

### ISSUE THREAD

**Issue by dcriado** [josemmo/Facturae-PHP#101]
Utilizando Facturae con OpenSSL 3.0.2, no conseguía añadir la firma al final del archivo xsig. Buscando la raíz del problema, me encontré con [**esta respuesta en StackOverflow**](https://stackoverflow.com/a/72600724/10338927) que no sólo explica la causa, sino que dice cómo convertir ciertos certificados p12 para que puedan ser leídos con OpenSSL 3.0.x.

Este **no es un problema de Facturae**, pero podría ocurrirle a otros usuarios a través de Facturae y por ello propongo dos acciones que ayuden a evitar quebraderos de cabeza:

1. Devolver el código de error de OpenSSL si `openssl_pkcs12_read` falla en este condicional, utilizando la función [openssl_error_string](https://www.php.net/manual/en/function.openssl-error-string.php)
https://github.com/josemmo/Facturae-PHP/blob/11554a608c17735390eb92d0cd7ea57a967db5d5/src/Common/KeyPairReader.php#L85

2. Añadir a la documentación de la [firma electrónica](https://josemmo.github.io/Facturae-PHP/firma-electronica/) una sección donde se advierta de la incompatibilidad de OpenSSL 3 con ciertos certificados. Quizás también aprovechando la respuesta de StackOverflow, dar pautas para convertir los archivos al nuevo formato. Esto fue lo que resolvió el problema en mi caso.

Muchas gracias por haber creado esta herramienta tan útil. Saludos.

**Comment by josemmo** [comment]
Hola @dcriado,

He añadido un aviso sobre este tema en la documentación.
