### ISSUE TITLE
Factura rectificativa

### ISSUE THREAD

**Issue by Yamilestebangarcia** [josemmo/Facturae-PHP#107]
Hola jose, estoy utilizando vuestro paquete, antes de nada darte las gracias por compartirlo.
¿una pregunta es posible crear una factura rectificativa?

un saludo y muchas gracias

**Comment by josemmo** [comment]
Hola @Yamilestebangarcia,

Ahora mismo no es posible, se tendría que implementar como una nueva funcionalidad.

**Comment by TheNocoder** [comment]
Estaba buscando la característica de rectificativa... ¿tenéis planes para implementarlo?

**Comment by NeoRazorX** [comment]
Me interesa también.

¿Valdría con añadir una función para indicar que es rectificativa, la original y el motivo? Se guarda eso en varias variables y al exportar se rellenan las etiquetas InvoiceClass, Corrective, InvoiceNumber, InvoiceSeriesCode, ReasonCode y ReasonDescription.

¿Voy bien o falta mucho más?

**Comment by josemmo** [comment]
Hola!

Ya está implementada esta funcionalidad en la rama `develop`. Se puede probar desde Composer:
```
composer require josemmo/facturae-php:dev-develop
```

La documentación está en [este enlace](https://github.com/josemmo/Facturae-PHP/blob/5e703e775f1cf5558575cc100916c03b5e0ec86a/doc/propiedades/rectificativas.md).
