### ISSUE TITLE
Es posible consultar las administraciones DIR3 y sus unidades, órgano gestor, etc?

### ISSUE THREAD

**Issue by santycg2002** [josemmo/Facturae-PHP#109]
Buenas...

Estoy buscando una librería que permita obtener la lista de administraciones públicas dadas de alta y sus correspondientes "órgano gestor", "unidad tramitadora", "oficina contable", etc.

No sé si es posible con esta librería.

Gracias y muy buen trabajo!

**Comment by josemmo** [comment]
Hola @santycg2002,

Para eso puedes usar el [directorio de organismos](https://face.gob.es/es/directorio/administraciones) de FACe, aunque una administración pública puede tener varias "relaciones" (combinaciones de OG, UT y OC). Lo normal es que estos datos te los proporcione el receptor de la factura.
