### ISSUE TITLE
Firma de factura con .CER y Passhare

### ISSUE THREAD

**Issue by manzsoluciones** [josemmo/Facturae-PHP#110]
Buenas!.

Esto no es una incidencia, más bien una consulta que no he conseguido resolver. He probado todas las formas que se me ocurren para rellenar todos los campos de firma respecto a su documentación, pero no he tenido suerte. También he consultado todas las menciones a la firma aquí indicadas y nada.

He recibido de mi cliente un archivo .CER y una CLAVE. He intentado aplicarlo de la siguiente forma:

`$fac->sign(
  'certificado.cer',
  null,
  'CLAVE'
);`

Y nada, no la adjunta. He buscado documentación para sacar la clave publica y privada y nada, todas mis pruebas infructuosas.

Podría indicarme como realizar esto o si de alguna forma necesito sacar los certificados de otra forma.

Gracias!

**Comment by josemmo** [comment]
Hola @manzsoluciones,

Los ficheros "*.cer" no suelen tener la clave privada, solo el certificado público. Para firmar hace falta la clave privada.

¿Qué error te da la librería? ¿Podrías compartir el código qué estás usando para generar/firmar la factura?

**Comment by manzsoluciones** [comment]
Buenas Josemo. Gracias por responder. Voy a indagar entonces donde conseguir la clave, imagino que en Facturae o FACe identificándote con el certificado.

Error como tal no da, simplemente genera el archivo sin firma y al enviarlo a comprobación de Facturae me da todo correcto menos la firma.

He usado tu código de ejemplo https://josemmo.github.io/Facturae-PHP/ejemplos/factura-simple.html ya que es algo sencillo lo que tengo que implementar, solo me falta ese tema del certificado.

**Comment by josemmo** [comment]
La clave privada no se puede descargar desde FACe o desde ninguna plataforma. Viene dentro del certificado (que suele ser un fichero "*.pfx") proporcionado por una entidad emisora autorizada, como la FNMT.

Si puedes iniciar sesión en FACe o en Cl@ve con certificado digital, entonces ya lo tienes instalado en tu ordenador. Solo tienes que exportarlo, si usas Windows, desde el administrador de certificados.

**Comment by manzsoluciones** [comment]
Buenas Josemo.
Gracias por la respuesta, como esto me lo pidió un cliente y pensé que seria tan fácil como aplicar archivo/passhare ni se me ocurrió probarlo.
Lo instale para intentar exportarlo en PFX, y no me dejaba (aparece deshabilitado en Windows). pero no se me ocurrió probarlo para iniciar sesión en FACe por ejemplo, y al probarlo hoy, zas, error de certificado. Asique seguramente vengan por ahí los problemas, le diré al cliente que consiga el PFX y listo.

Gracias por las respuestas!, y un super buen trabajo. Espero animarme como tu a subir librerías publicas.
