### ISSUE TITLE
Error al enviar facturas (entorno pruebas)

### ISSUE THREAD

**Issue by santycg2002** [josemmo/Facturae-PHP#111]
Hola...

Sigo probando la librería. Ya puedo generar y firmar facturas sin problema, pero no consigo realizar el envío a FACe.

El error que obtengo es el siguiente:
Error 300: El certificado electrónico no está dado de alta en FACe. Para la presentación automatizada de facturas es necesario registrarse previamente en https://face.gob.es/es/proveedores

El certificado que uso para la firma y para el envío sí está dado de alta en el portal. De hecho si voy a ese enlace y pulso "Gestión de certificados", puedo ver el certificado (el mismo) y un administrador.

Como estoy haciendo pruebas, la factura generada tiene datos ficticios y no coincide el emisor de la factura con el nombre del "administrador" creado en el portal. No sé si se debe a eso o a otra cosa.
El certificado es válido y renovado recientemente (caduca en 2026).

¿Quizás es porque estoy usando el entorno de pruebas, no el de producción? ¿O me falta algo por hacer?

Gracias

**Comment by josemmo** [comment]
Duplicado de #74.

El entorno de producción de FACe es independiente del entorno de staging.
