### ISSUE TITLE
Factura simplificada

### ISSUE THREAD

**Issue by dixitalmedia** [josemmo/Facturae-PHP#112]
Hola

En primer lugar muchas gracias por tu trabajo.

Estoy haciendo un plugin para WooCommerce basado en tu librería. 
Este plugin requiere, entre otros, _PDF Invoices & Packing Slips_ para generar primero la factura en PDF.
Seguramente lo libere en el repositorio de WordPress.org pero quiero dejarlo antes funcional al 100% y además quiero quitar la dependencia de otro plugin, que es de pago, que también es necesario en este momento.

Hasta aquí todo bien, aunque con ciertas limitaciones.
Ya puedo generar facturas, pero sin RE ni IRPF porque esto depende de WooCommerce que no lo contempla de serie y para eso estoy preparando una nueva versión.
Así como otras limitaciones existentes porque WooCommerce no diferencia personas físicas de jurídicas. Quizás lo haga validando NIF, campo que tampoco existe pero que he añadido, aunque no sería aplicable a extranjeros. 
Otra opción es creando nuevos roles de usuario: _customer_, _customer_business_ y _customer_retail_ (para el RE).
Mi idea es hacerlo de manera lo menos intrusiva posible y que no cambie cualquier configuración existente en las webs donde se instale.

Lo que sí veo por parte de tu librería es que no hay forma de implementar todos los tipos de facturas existentes: **completa u ordinaria y simplificada**.

Por lo que veo **InvoiceDocumentType** está hardcodeado para la _factura completa_ y es muy común que en web se generen ventas anónimas sin datos de comprador o con datos a medias.
WooCommerce no tiene NIF y aun añadiéndolo con un hook o plugin mucha gente lo ignora y no lo cubre.

```
    // Add invoice data
    $xml .= '<Invoices><Invoice>';
    $xml .= '<InvoiceHeader>' .
        '<InvoiceNumber>' . $this->header['number'] . '</InvoiceNumber>' .
        '<InvoiceSeriesCode>' . $this->header['serie'] . '</InvoiceSeriesCode>' .
        '<InvoiceDocumentType>FC</InvoiceDocumentType>' .
        '<InvoiceClass>OO</InvoiceClass>' .
      '</InvoiceHeader>';
```
He hecho pruebas y factura-e no valida facturas sin datos del "buyer" completos.

Veo otro hilo [https://github.com/josemmo/Facturae-PHP/issues/107](url) sobre la Factura rectificativa y creo que está también relacionado con este, ya que el **InvoiceClass** también está hardcodeado.

¿Hay planes de hacer avances en estos puntos?

Muchas gracias

Saludos,
Jairo

**Comment by josemmo** [comment]
Hola Jairo,

> Lo que sí veo por parte de tu librería es que no hay forma de implementar todos los tipos de facturas existentes: completa u ordinaria y simplificada.

Lo muevo al issue #113.

---

> He hecho pruebas y factura-e no valida facturas sin datos del "buyer" completos.

Aunque un documento se declare como factura simplificada (tipo "FA"), sigue siendo obligatorio incluir los datos del vendedor y del comprador.

**Comment by dixitalmedia** [comment]
Para el caso de la FA voy a definir entonces un Comprador por defecto para los casos que no existan datos.
Como el NIF no se comprueba, solo que tenga valor, asignaré 00000000
Supongo que tarde o temprano deberían estandarizar estos detalles que por lo que he leído ahora no lo contempla la norma, o al menos no lo he encontrado.
