### ISSUE TITLE
Error 100 al presentar factura.

### ISSUE THREAD

**Issue by fjsampe** [josemmo/Facturae-PHP#116]
Buenas tardes. 
Tras estar funcionando correctamente su libreria durante casi 1 año. La semana pasada nos encontramos con el error 100 al presentar una factura en FACE, el cual indica "La firma de la petición SOAP no es válida", pero desconozco a que se refiere puesto que la factura está presentada según se desprende del correo recibido a continuación por el organismo correspondiente. El problema es que con este error, evidentemente no adjunta el número de registro de la factura en FACE.
Quisiera saber si este error es habitual, general o es debido a algún cámbio reciente en el organismo encargado de recepcionar las facturas electrónicas. 
Nota: Ver. 1.6.0 de facturae-PHP

**Comment by fjsampe** [comment]
Solucionado. Ese error puede que sea genérico y no especifíca el problema real. En este caso solamente era un dato en el centro administrativo erróneo.

**Comment by fjsampe** [comment]
El fichero xsig lo he validado en Face, de hecho está registrada la factura, pero no entiendo porqué devolvió este error en esta factura en cuestión. Posiblemente time-out?

**Comment by josemmo** [comment]
Hola @fjsampe,

Lo primero que te recomiendo es actualizar a la última versión de la librería, la v1.6.0 ya tiene casi dos años.

¿Cuándo se obtiene el error 100? ¿Es al llamar al método [`$face->sendInvoice()`](https://josemmo.github.io/Facturae-PHP/envio-y-recepcion/face.html#face-sendinvoiceemail-invoice-attachments)? ¿Si llamas a [`$face->getStatus()`](https://josemmo.github.io/Facturae-PHP/envio-y-recepcion/face.html#face-getstatus) obtienes el mismo error?

**Comment by josemmo** [comment]
Cerrado por inactividad.
