### ISSUE TITLE
Devoluciones con descuentos

### ISSUE THREAD

**Issue by SolucionesInformaticasMJ** [josemmo/Facturae-PHP#117]
A la hora de hacer facturas de devolución o abono (negativas), si esta posee algún tipo de descuento (En línea o general), se vuelve positivo de forma automática y el total de los importes no es correcto.

¿Alguna idea de si es un comportamiento esperado o es un bug?

**Comment by josemmo** [comment]
Hola @SolucionesInformaticasMJ,

La forma en la que se gestionan los descuentos en la librería es la misma para ambos casos.
¿Podrías pasar un código en PHP que genere una factura de ejemplo en la que aparezca este problema?

**Comment by SolucionesInformaticasMJ** [comment]
Buenos días, nos hemos dado cuenta que era problema de los porcentajes negativos. No es un error del paquete.
