### ISSUE TITLE
Implementar campos `ThirdParty`

### ISSUE THREAD

**Issue by aprat84** [josemmo/Facturae-PHP#118]
Buenas!

Seria posible implementar los campos `ThirdParty`?

Básicamente es la identificación de un tercero que es quien genera y firma la factura.
Esto iría genial en sistemas con multiples clientes, para facilitarles la vida y no tener que almacenar y gestionar cada uno de sus certificados.

Dejo enlaces del PDF y XSD de la especificación versión 3.2.2:
[Descripción de campos [PDF] [1,35 MB]](https://www.facturae.gob.es/formato/Versiones/Esquema_castellano_v3_2_x_06_06_2017_unificado.pdf)
[Esquema XSD formato Facturae 3.2.2 [XML] [185,61 KB]](https://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml)

**Comment by josemmo** [comment]
Hola @aprat84,

Acabo de añadir esta funcionalidad a la librería. Puedes probarla desde la rama `develop`:

```
composer require josemmo/facturae-php:dev-develop
```

Tienes la documentación en [este enlace](https://github.com/josemmo/Facturae-PHP/blob/420a61b16fd69c7ff31c740add7094807926e4d1/doc/entidades/terceros.md).

**Comment by aprat84** [comment]
Genial!

Lo probaremos en breve, si no es esta semana será la siguiente.

Muchas gracias!
