### ISSUE TITLE
Error con firma

### ISSUE THREAD

**Issue by chusmsanchez** [josemmo/Facturae-PHP#119]
Hola buenas.

Primero de todo muchas gracias por el aporte de la libreria ayuda mucho.

Tengo un problemilla, he intentado firmar al facturaE pero cuando se genera el fichero xsig y lo visualizo como xml, no veo en ninguna etiqueta la firma inscrustada en el fichero (supuestamente usa la etiqueta <ds:Signature ...... >.

He probado tanto con el certificado (supuestamente de prueba) que hay adjunto en la librería como el mío personal, tanto en formato pem como en formato p12, pero sigue ocurriendo el mismo problema.

Espero me puedan echar una mano.

Gracias!

**Comment by chusmsanchez** [comment]
Bueno, me voy a autoresponder por si puedo ayudar a algún despistado como yo.

El problema lo tenía porque ponía mal la contraseña. Igualmente para trabajar con p12 he utilizado la siguiente línea de código:

`$encryptedStore = file_get_contents("tests/certs/certificadoChus.p12");
$fac->sign($encryptedStore, null, "15416404Xjesus");`

**Comment by chusmsanchez** [comment]
Bueno, me voy a autoresponder por si puedo ayudar a algún despistado como yo.

El problema lo tenía porque ponía mal la contraseña. Igualmente para trabajar con p12 he utilizado la siguiente línea de código:

$encryptedStore = file_get_contents("tests/certs/NOMBRE_DEL_FICHERO.p12"); $fac->sign($encryptedStore, null, "LA_CONTRASEÑA_DEL_CERTIFICADO");

**Comment by chusmsanchez** [comment]
Hola buenos días.

No se si hago lo correcto reabriendo este post, porque tengo error con la firma aunque sea por diferente motivo.

En este caso, si muevo de directorio el fichero del certificado .p12, no me realiza la firma. Por defecto veo que está dentro de los directorios "tests/certs".

Si por ejemplo quiero alojar en otro directorio el .p12 no me funciona. (He probado lo siguiente: ../../data/1/cert/FICHERO.p12 .

También he intentado mover el fichero .p12 en el directorio "tests/FICHERO.p12" y tampoco funciona.

Es decir, que si lo saco de "tests/certs" no funciona. ¿Alguna solución?


Gracias.

**Comment by josemmo** [comment]
Hola @chusmsanchez,

Los certificados no es que se guarden en el directorio "tests/certs" por defecto, sino que los que hay ahí dentro son para ejecutar los tests unitarios de la librería. **No se deben usar para firmar facturas reales**.

El tema de las rutas de ficheros es completamente dependiente de tu sistema. Si usas rutas relativas, tienen que ser relativas al directorio desde donde estás ejecutando el script. Por eso suele ser mejor usar rutas absolutas. En PHP tienes la constante [`__DIR__`](https://www.php.net/manual/en/language.constants.magic.php#constant.dir) que siempre tiene la ruta absoluta del fichero desde donde se llama, quizá te sirva.

Pero vamos, que esto último no es algo propio de la librería, es que PHP funciona así.

**Comment by chusmsanchez** [comment]
Buenas de nuevo.

Evidentemente no uso el certificado de pruebas, si no que añado a la carpeta "tests/certs" mi certificado para realizar las pruebas pertinentes.

Cuando saco el certificado mio a otro directorio, usando incluso la ruta absoluta, no me firma el fichero generado, es lo que me extraña. 

Le daré otra vuelta a ver.

Gracias, os mentengo informados.
