### ISSUE TITLE
Batuz Asturias

### ISSUE THREAD

**Issue by joebordes** [josemmo/Facturae-PHP#121]
Hola

Quería saber si esta librería sirve también para el formato Batuz de Asturias.

> Necesitaría alguna herramienta que me permitiese hacer facturas electrónicas válidas tanto para el face como para el sistema batuz que son los sistemas públicos con los que trabajamos a día de hoy. 

Gracias

**Comment by josemmo** [comment]
Hola @joebordes,

Esta librería solo permite trabajar con documentos de FacturaE. No estoy muy familiarizado con BATUZ, pero hasta donde se, creo que no ofrece compatibilidad con FacturaE.
