### ISSUE TITLE
Cambio en documentación "uso sin composer"

### ISSUE THREAD

**Issue by webolot** [josemmo/Facturae-PHP#122]
Segun se comentó unas semanas atrás [aquí](https://github.com/josemmo/Facturae-PHP/issues/115) se tendria que arreglar la documentación.  

En teoría [ya está arreglado](https://github.com/josemmo/Facturae-PHP/commit/c7183ea21c68ec66394287d6f47845634004e51a)

Pero no lo veo reflejado ni [aquí](https://github.com/josemmo/Facturae-PHP/blob/master/doc/ejemplos/sin-composer.md) ni [aquí](https://josemmo.github.io/Facturae-PHP/ejemplos/sin-composer.html)

![image](https://user-images.githubusercontent.com/80535144/224738203-be8d95e7-45f3-4933-ab00-0f4e27bbc1be.png)

![image](https://user-images.githubusercontent.com/80535144/224738160-a44a5649-df98-46c5-af69-4de278fe7d49.png)

**Comment by josemmo** [comment]
Hola @webolot,

Los cambios ya está en la rama "develop" pero todavía no han sido mergeados a la rama principal, por eso no aparecen en la web de la documentación.
