### ISSUE TITLE
"Class 'FacturaeItem' not found" sin composer

### ISSUE THREAD

**Issue by webolot** [josemmo/Facturae-PHP#123]
Con el uso sin composer, con la siguiente linea para añadir un producto todo funciona perfectamente...

`$fac->addItem("Lámpara de pie", 20.14, 3, Facturae::TAX_IVA, 21);`

pero al intentar usar la API avanzada (necesito añadir el IRPF), con por ejemplo ...

```
$fac->addItem(new FacturaeItem([
    "name" => "Nombre",
    "articleCode" => "A1234",
    "quantity" => 2,
    "unitPriceWithoutTax" => 100,
    "discounts" => [
        ["reason" => "Descuento del 20%", "rate" => 20]
    ],
    "charges" => [
       ["reason" => "Recargo de equivalencia", "rate" => 5.2, "hasTaxes" => false] // <----- Recargo de equivalencia
    ],
    "taxes" => [
        Facturae::TAX_IVA => 21,
        Facturae::TAX_IRPF => 19
    ]
]));
```

Aparece este error ...

> Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'FacturaeItem' not found in index.php:63\nStack trace:\n#0 {main}\n  thrown in index.php on line 63'

**Comment by josemmo** [comment]
Hola @webolot,

Supongo que te falta añadir esta línea al script:
```php
use josemmo\Facturae\FacturaeItem;
```
