### ISSUE TITLE
Añadir SpecialTaxableEvent a líneas de factura (concepto sin impuestos)

### ISSUE THREAD

**Issue by josepgv** [josemmo/Facturae-PHP#124]
Hola @josemmo 

Gracias por crear y mantener esta librería, nos está siendo muy útil.

Tenemos una necesidad de en algunas líneas de factura poder añadir la información relativa a la exención de impuestos de la misma como permite el programa facturae:

![image](https://user-images.githubusercontent.com/7456368/225933756-ca19ed67-1773-44d0-a8ba-df959f0221ea.png)

En el XML se traduce en que en cada InvoiceLine se añade una clave [SpecialTaxableEvent (página 43)](https://www.facturae.gob.es/formato/Versiones/Esquema_castellano_v3_2_x_06_06_2017_unificado.pdf) con un par de campos.

No se si hay alguna manera actualmente de hacer esto, si no, yo he probado haciendo unas modificaciones para permitirlo y podría hacer una PR si te parece bien.

**Comment by josemmo** [comment]
Hola @josepgv,

Ahora mismo la librería no lo permite. Lo apunto como nueva feature para la próxima release.

**Comment by josemmo** [comment]
Acabo de implementar esta funcionalidad en la librería y ya se puede probar desde la rama `develop`:

```
composer require josemmo/facturae-php:dev-develop
```

La documentación está en [este enlace](https://github.com/josemmo/Facturae-PHP/blob/94affacbd7f77c4860b44b48f234b631b97fe3f8/doc/productos/impuestos.md#fiscalidad-especial).
