### ISSUE TITLE
Firma incorrecta - FACe

### ISSUE THREAD

**Issue by oriolvinals** [josemmo/Facturae-PHP#126]
Buenas José!

Primero que todo, gracias por la libería.

Tengo un certificado `.p12` válido para firmar las facturas¹. Al generar la factura con la firma electrónica no genera ningún problema, pero una vez quiero validar que la firma sea correcta (en este caso con FACe) me dice que es incorrecta.

![image](https://user-images.githubusercontent.com/58267656/235893366-512f20a8-191f-455a-8c3f-03c0a7a71998.png)

Si solo válido el formato, sí que lo hace correctamente.
He intentado mil cosas..., pasar el `.p12` a `.pem` con certificado y clave privada y también falla...

Nos puedes echar una mano? Muchas gracias!

¹ Con el certificado `.p12` con una factura `.xml` usando la aplicación de `AutoFirma` y validando con FACe, ahi si que me dice que la firma es correcta.

**Comment by josemmo** [comment]
Hola @oriolvinals,

¿Puedes pasar un ejemplo de una factura generada con la librería que te de problemas al validar la firma?

**Comment by MrTrabu** [comment]
Hola

Estoy exactamente en la misma situación. Utilizo la librería solo para la firma (una maravilla de código, mucha gracias!) pero por más que lo he revisado no doy con ello. He añadido etiquetas que me daba el autofirma, cambiado la fecha/hora de la marca que vi que a algunos les habían comentado que el +2 daba problemas (el de autofirma lo lleva y no da problemas), y varias modificaciones más sin llegar a poder validar la firma.

Si lo resolveis os agradecería que indicarais a que es debido a ver si puedo llegar a validarla. El esquema es correcto, me falla la validación de firma. 

Muchas gracias!

PD. Si necesitas ver el xml o xsig me comentas.

**Comment by MrTrabu** [comment]
Hola @josemmo 

Si, lo había visto. he probado con una única etiqueta X509Certificate y con las que tenia el certificado (3), con certificados de FNMT y de Izenpe ficticios de desarrollo, he modificado también el orden del transform de enveloped-signature que leí en algún sitio que debía ir el primero si había varios... He hecho varias pruebas pero no doy con ello, no se que puede ser.

En el validador del Ministerio de Industria me da:
En la validación de firma electrónica: Firma inválida (firma y/o certificados alterados). Sintaxis y semántica son correctos.
En la integridad: Los datos han sido alterados o existe un error en la firma

En https://signasuite.aoc.cat/signasuite/validateSignature:
Resultat: urn:oasis:names:tc:dss:1.0:resultminor:invalid:incorrectSignature
Data de validació:
Tipus de signatura: XML/XAdES Enveloped
Y en los datos del certificado si aparece el nombre, emisor y nivel de clasificación correctamente, pero no la fecha de expiración del certificado...

Seguiré probando a ver si doy con ello, pero no se me ocurre que puede ser...

Muchas gracias

**Comment by josemmo** [comment]
@MrTrabu, pasa un ejemplo de una factura de prueba firmada que de problemas de validación para poder revisarla en detalle.

**Comment by MrTrabu** [comment]
[xsig.zip](https://github.com/josemmo/Facturae-PHP/files/11411951/xsig.zip)
Hola José Miguel

Adjunto xsigs de la misma factura y certificado, uno validado con autofirma y el otro generado con la librería. La parte del data, modulus y demás coinciden, no así la parte de SignedInfo y SignatureValue

Gracias!

**Comment by josemmo** [comment]
Hola @MrTrabu,

La factura está claro que no la estás generado con Facturae-PHP, pero es que tampoco parece que estés usando la clase [FacturaeSigner](https://josemmo.github.io/Facturae-PHP/firma-electronica/firma-avanzada.html) para hacer la firma.

Al final del XML que subes ("A99800310_21_8_errorvalidacion.xsig") hay una indentación con 4 espacios que Facturae-PHP no mete pero que está ahí:
```xml
</xades:QualifyingProperties>
    </ds:Object>
    </ds:Signature></fe:Facturae>
```

Debería ser:
```xml
</xades:QualifyingProperties></ds:Object></ds:Signature></fe:Facturae>
```

¿Seguro que no estás alterando el documento después de firmarlo? Si alteras el XML aunque sea en un solo bit después de firmarlo, la firma ya no será válida.

**Comment by MrTrabu** [comment]
Hola José Miguel

Solucionado. Desesperado y viendo lo que me devolvía autofirma efectivamente estaba modificando el xml (esos 4 espacios y cerrando los tags con /> en algunos casos). He empezado todo de cero de nuevo con FacturaeSigner y me ha validado la firma a la primera. En un principio estaba utilizando un certificado ficticio de Izenpe y no se si habrá sido por eso, despúes empecé con otro certificado real de la FNMT pero ya estaba tocado el código. Me ha sido de gran ayuda la pista de los 4 espacios para darme cuenta de la cantidad de pruebas que estaba haciendo sin sentido y  valorar en empezar de nuevo todo el proceso de firma, te lo agradezco. El código como te dije anteriormente es perfecto y muchas veces cuando te obcecas con algo es mejor parar y no dar palos de ciego.

Muchas gracias!

**Comment by josemmo** [comment]
Ok, me alegro de que ya esté solucionado! Doi por cerrado el issue.
