### ISSUE TITLE
Recepción de facturas de proveedor

### ISSUE THREAD

**Issue by BorjaMateo95** [josemmo/Facturae-PHP#127]
Buenas tardes,
Es posible recibir facturas que un proveedor me emita a través de FACeB2B ?
Como seré notificado que un proveedor me ha emitido una factura ?

Gracias

**Comment by josemmo** [comment]
Hola @BorjaMateo95,

Sí, es posible. Tienes la documentación en [este enlace](https://josemmo.github.io/Facturae-PHP/envio-y-recepcion/faceb2b.html).

**Comment by BorjaMateo95** [comment]
Hola @josemmo,
Muchas gracias por la respuesta.
He revisado la documentación y no he visto un método que devuelva tus facturas que te han enviado un proveedor...
Tampoco entiendo como será notificado el cliente de que tiene una factura pendiente.

Gracias

**Comment by josemmo** [comment]
FACeB2B no te notifica, sino que tienes que llamar a `getRegisteredInvoices()` para listar las nuevas facturas de forma similar a cómo funciona el protocolo POP/IMAP en correo electrónico.
Después lees los datos de una factura con `downloadInvoice()` y por último confirmas su descarga o la rechazas.
