### ISSUE TITLE
Error en Traits

### ISSUE THREAD

**Issue by AitorCheVaq** [josemmo/Facturae-PHP#128]
Hola,

Estoy en un proyecto usando tu paquete y al acceder a los métodos de los Trait no me deja usarlos y no he modificado nada del código.

El código en la clase Facturae está puesto así:
```php
<?php
namespace josemmo\Facturae;

use josemmo\Facturae\FacturaeTraits\PropertiesTrait;
use josemmo\Facturae\FacturaeTraits\UtilsTrait;
use josemmo\Facturae\FacturaeTraits\SignableTrait;
use josemmo\Facturae\FacturaeTraits\ExportableTrait;
```

Donde lo llamo:
```php
$fac = new josemmo\Facturae\Facturae();

        $sql_factura = "consultaSQL";
        
        $consulta = odbc_exec($con_400, $sql_factura);
        
        if(odbc_fetch_row($consulta)){
            
            $fac->setNumber(trim($serie_factura), odbc_result($consulta, "valor"));
```

Y al ejecutar en la consola aparece esto:
```console
Fatal error:  Uncaught Error: Call to undefined method josemmo\Facturae\Facturae::setNumber()
```

La versión de PHP es 8.0.7.

Gracias.

**Comment by josemmo** [comment]
Hola @AitorCheVaq,

¿Qué versión de la librería usas? ¿Has probado a ejecutar el código de los [ejemplos de la documentación](https://josemmo.github.io/Facturae-PHP/ejemplos/factura-simple.html)? ¿Al ejecutar los ejemplos te aparece algún error?

**Comment by AitorCheVaq** [comment]
Hola, al final pude resolver el error añadiendo el " require_once 'autoload'; " a la clase Facturae, pero me ha aparecido otro error:
```console
Fatal error:  Uncaught Error: Call to undefined method josemmo\Facturae\Common\FacturaeSigner::loadPkcs12() in josemmo\facturae-php\src\FacturaeTraits\SignableTrait.php:72
```

Pero en la clase SignableTrait está esto:
```php
<?php
namespace josemmo\Facturae\FacturaeTraits;

use josemmo\Facturae\Common\FacturaeSigner;

/**
 * Implements all properties and methods needed for an instantiable
 * Facturae to be signed and time stamped.
 */
trait SignableTrait {
```
```php
public function sign($storeOrCertificate, $privateKey=null, $passphrase='') {
    $signer = $this->getSigner();
    if ($privateKey === null) {
      $signer->loadPkcs12($storeOrCertificate, $passphrase); // <- linea 72
    } else {
      $signer->addCertificate($storeOrCertificate);
      $signer->setPrivateKey($privateKey, $passphrase);
    }
    return $signer->canSign();
  }
```

Y si hago uso de "use" no detecta "KeyPairReaderTrait" en la carpeta Common ni tampoco con el "require_once".

La versión es la última y lo que te estoy mostrando es lo que he probado con el código de ejemplo, ya que sale lo mismo.


> Hola @AitorCheVaq,
> 
> ¿Qué versión de la librería usas? ¿Has probado a ejecutar el código de los [ejemplos de la documentación](https://josemmo.github.io/Facturae-PHP/ejemplos/factura-simple.html)? ¿Al ejecutar los ejemplos te aparece algún error?

**Comment by josemmo** [comment]
@AitorCheVaq,

La librería no se usa así, pero ni esta ni ninguna que use un autoloader como Composer, por eso te da errores.

No tienes que modificar el código de los ficheros de Facturae-PHP, el `require_once "autoload.php"` lo tienes que poner en tu script.

**Comment by AitorCheVaq** [comment]
> @AitorCheVaq,
> 
> La librería no se usa así, pero ni esta ni ninguna que use un autoloader como Composer, por eso te da errores.
> 
> No tienes que modificar el código de los ficheros de Facturae-PHP, el `require_once "autoload.php"` lo tienes que poner en tu script.

Ya lo he cambiado, pero el error permanece. En tu código de github pone que el método "loadPkcs12" es tipo "KeyPairReaderTrait" pero al importarlo me pone que es tipo "FacturaeSigner", entonces no lo comprendo.

**Comment by AitorCheVaq** [comment]
> @AitorCheVaq,
> 
> La librería no se usa así, pero ni esta ni ninguna que use un autoloader como Composer, por eso te da errores.
> 
> No tienes que modificar el código de los ficheros de Facturae-PHP, el `require_once "autoload.php"` lo tienes que poner en tu script.

Ya lo he cambiado, pero el error permanece. En tu código de github pone que el método "loadPkcs12" es tipo "KeyPairReaderTrait" pero al importarlo me pone que es tipo "FacturaeSigner", entonces no lo comprendo.
Ahí si que no modifiqué código, sólo fue en la clase Facturae y fue esa línea.

**Comment by josemmo** [comment]
@AitorCheVaq, los traits no son clases. Las clases usan traits. No deberías tener que importar los traits de la librería para nada.

Por lo que describes, esto es un problema de tu entorno de aplicación, y ahí ya no te puedo ayudar porque se me escapa cómo lo tienes montado.

Insisto en qué revises el autoload o la configuración de Composer de tu app, porque si te sale el error "call to undefined method" tiene que ser algo de eso.

**Comment by AitorCheVaq** [comment]
> @AitorCheVaq, los traits no son clases. Las clases usan traits. No deberías tener que importar los traits de la librería para nada.
> 
> Por lo que describes, esto es un problema de tu entorno de aplicación, y ahí ya no te puedo ayudar porque se me escapa cómo lo tienes montado.
> 
> Insisto en qué revises el autoload o la configuración de Composer de tu app, porque si te sale el error "call to undefined method" tiene que ser algo de eso.

A ver, no son clases, es que yo las llamo así porque es la primera vez que uso traits, pero me refería a los traits, en ningún momento los importo, los tengo en el mismo programa y tengo el código de prueba que dijiste, solo hago un ' require_once "facturae" ' y un ' require_once "autoload" ', todos los métodos de los traits funcionan perfectamente pero de alguna manera los de signableTrait son los que fallan por lo que te he comentado anteriormente, pone que el método loadPkcs12() lo toma como del trait donde se le llama y no del trait KeyPairReaderTrait. Por eso te pregunto, porque esto es nuevo para mí y mis compañeros que son más avanzados en el campo tampoco han podido resolverlo.

**Comment by josemmo** [comment]
Pero a ver, ¿a qué refieres con que solo haces un `require_once "facturae"` ' y un `require_once "autoload"`? Porque salvo que tengas un fichero que se llama "facturae" y otro con el nombre de "autoload" (sin extensión), eso es muy raro.

Lo que tienes que hacer, si usas Composer en este proyecto, es añadir **solo una línea** a tu script:
```php
require_once 'ruta/hacia/vendor/autoload.php';
```

Si en tu organización no usáis Composer, échale un vistazo a [este ejemplo](https://josemmo.github.io/Facturae-PHP/ejemplos/sin-composer.html) de la documentación.

**Comment by AitorCheVaq** [comment]
> Pero a ver, ¿a qué refieres con que solo haces un `require_once "facturae"` ' y un `require_once "autoload"`? Porque salvo que tengas un fichero que se llama "facturae" y otro con el nombre de "autoload" (sin extensión), eso es muy raro.
> 
> Lo que tienes que hacer, si usas Composer en este proyecto, es añadir **solo una línea** a tu script:
> 
> ```
> require_once 'ruta/hacia/vendor/autoload.php';
> ```
> 
> Si en tu organización no usáis Composer, échale un vistazo a [este ejemplo](https://josemmo.github.io/Facturae-PHP/ejemplos/sin-composer.html) de la documentación.

Me refiero a que uso ' require "facturae" ' porque tu librería la tengo dentro de vendor (ahí es donde se coloca automáticamente cuando en la consola hago 'composer require josemmo/facturae') y si no lo pongo no detecta el 'facturae.php', entonces por eso lo uso, y he probado tanto usando composer como sin usar composer y me da el mismo error

**Comment by AitorCheVaq** [comment]
> @AitorCheVaq, ni mi librería ni Composer se usa así.
> 
> No tienes que añadir la línea `require "facturae"` en ninguna parte. Insisto una vez más en que tienes que añadir esta línea a tu app o script:
> 
> ```
> require_once 'ruta/hacia/vendor/autoload.php';
> ```
> 
> El autoloader se requiere **una sola vez** en toda tu aplicación y para todas las librerías. Si tu proyecto ya usa otras dependencias, no tienes que volver a añadir la línea.
> 
> No añadas la línea `require_once "facturae"`. Aunque estuviera bien escrito (por ejemplo, `require_once "vendor/josemmo/Facturae-PHP/src/Facturae.php"`), daría error igual puesto que Facturae-PHP espera cargar el resto de ficheros de la propia librería con Composer.

ok ya he quitado `require "facturae"` y he dejado únicamente tu código de prueba y el `require_once 'ruta/hacia/vendor/autoload.php';`. El error persiste. ¿Cómo puedo solucionarlo?

**Comment by josemmo** [comment]
@AitorCheVaq, no lo sé.

Puede ser por cualquier cosa: que has puesto mal la ruta hacia el fichero "autoload.php", que en tu proyecto no usáis Composer, etc. Como no tengo acceso al código, no tengo forma de saberlo con un solo mensaje de error.

Pregunta a tus compañeros, este foro está para notificar fallos y resolver dudas de la librería, no para resolver dudas de PHP en general.

**Comment by AitorCheVaq** [comment]
> @AitorCheVaq, no lo sé.
> 
> Puede ser por cualquier cosa: que has puesto mal la ruta hacia el fichero "autoload.php", que en tu proyecto no usáis Composer, etc. Como no tengo acceso al código, no tengo forma de saberlo con un solo mensaje de error.
> 
> Pregunta a tus compañeros, este foro está para notificar fallos y resolver dudas de la librería, no para resolver dudas de PHP en general.

Al final lo he conseguido resolver, porque en el trait "SignableTrait" se encuentran los use:
```php
<?php
namespace josemmo\Facturae\FacturaeTraits;

use josemmo\Facturae\Common\FacturaeSigner;
use josemmo\Facturae\Common\XmlTools;
```

y parece que al no estar el ```use josemmo\Facturae\Common\KeyPairReaderTrait;``` como que no detecta el método de dicho trait, así que lo he añadido y ahora lo detecta, así que no creo que tenga que ver con el php en sí.

**Comment by josemmo** [comment]
En `SignableTrait` no aparece esa línea porque literalmente ese fichero no usa `KeyPairReaderTrait`.

**Comment by AitorCheVaq** [comment]
> En `SignableTrait` no aparece esa línea porque literalmente ese fichero no usa `KeyPairReaderTrait`.

Pero usa el método `` LoadPkcs12() `` que pertenece a `` KeyPairReaderTrait `` entonces tu código contradice lo que estás diciendo.

**Comment by josemmo** [comment]
`SignableTrait` llama a `FacturaeSigner::loadPkcs12()`, por eso usa esa clase y no el trait que dices.

En fin, yo he intentado explicarlo lo mejor que he podido aunque creo que no lo he conseguido. Si haciendo ñapas has conseguido hacer funcionar tu aplicación, pues perfecto. Pero creo que en algún momento habría que dar la conversación por cerrada.
