### ISSUE TITLE
firmar factura con certificado local del cliente

### ISSUE THREAD

**Issue by josej69git** [josemmo/Facturae-PHP#129]
Hola. por medio de apache2 y php con los parámetros de apache:
    SSLVerifyClient optional_no_ca
    SSLVerifyDepth 1
    SSLOptions +StdEnvVars +ExportCertData
tengo la posibilidad de recuperar en el servidor el certificado que seleccione el cliente en su navegador, por lo tanto dispongo en PHP de una variable con:
-----BEGIN CERTIFICATE-----
MIII0TCCB7mgAwIBAgIQHAgKm8zkoUZkIsP5YP7FIjANBgkqhkiG9w0BAQsFADBN
MQswCQYDVQQGEwJFUzERMA8GA1UECgwIRk5NVC1SQ00xDjAMBgNVBAsMBUNFUkVT
MRswGQYDVQQDDBJBQyBSZXByZXNlbnRhY2nDs24wHhcNMjMwMzI4MTAzOTUzWhcN
MjUwMzI4MTEzOTUzWjCCARwxWTBXBgNVBA0MUFJlZzozMDAxMSAvSG9qYTpN ... ...
-----END CERTIFICATE-----
¿es posible usar este certificado para la firma?
El proceso de firma propuesto por lo que creo implica hacer un upload del certificado para poder usarlo, y por temas de seguridad y privacidad con el proceso que expongo aquí habría menos problemas ya que no subimos un archivo a nuestro servidor sino que cuando queremos firmar tenemos que seleccionar nuestro certificado y no queda nada en el servidor...

**Comment by josemmo** [comment]
Hola @josej69git,

No es posible firmar solo con esa información. Se necesita la clave privada asociada al certificado, que no sale del dispositivo cliente.

Para tu caso de uso, te recomiendo que uses [AutoScript](https://administracionelectronica.gob.es/ctt/clienteafirma/descargas), que es la integración de Autofirma para navegadores modernos y el sucesor de Miniapplet.

**Comment by josej69git** [comment]
Estupendo muchas gracias por todo.
