### ISSUE TITLE
ResidenceTypeCode siempre es R independientemente del país del cliente

### ISSUE THREAD

**Issue by isidoroaguilera** [josemmo/Facturae-PHP#130]
ResidenceTypeCode debería ser R si el cliente es español, U si es de otro país intracomunitario, E fuera de europa.

En el XML se graba siempre R.

getXML() en FacturaeParty:
`<ResidenceTypeCode>R</ResidenceTypeCode>`

**Comment by josemmo** [comment]
Hola @isidoroaguilera,

Gracias por reportarlo! Me lo apunto para añadir un método que permita editar el campo.
