### ISSUE TITLE
importar xml?

### ISSUE THREAD

**Issue by deook** [josemmo/Facturae-PHP#132]
Se podría importar una factura? el xml? y poder extraer todos sus datos buyers, sellers, items...

**Comment by Eseperio** [comment]
La librería no lo soporta actualmente, pero si todos aportamos podríamos conseguirlo.

**Comment by josemmo** [comment]
Hola @deook,

Para leer una factura puedes usar las funciones que vienen con PHP para parsear XML. Por ejemplo, con este código puedes obtener el CIF del receptor:
```php
$xml = file_get_contents(__DIR__ . '/factura.xsig');
$xml = new SimpleXMLElement($xml);

$taxNumber = (string) $xml->Parties->BuyerParty->TaxIdentification->TaxIdentificationNumber;
echo "Tax number is $taxNumber\n";
```

Como usar estas funciones es un poco *verbose* a veces, también puedes usar otra librería mía (un poquito de promoción) que simplifica el tratamiento de documentos XML.

Para instalar la librería:
```
composer require josemmo/uxml
```

Un ejemplo de uso:
```php
$xml = file_get_contents(__DIR__ . '/salida-3.2.2-PKCS12.xsig');
$xml = \UXML\UXML::fromString($xml);

$taxNumber = $xml->get('Parties/BuyerParty/TaxIdentification/TaxIdentificationNumber')->asText();
echo "Tax number is $taxNumber\n";
```
