### ISSUE TITLE
Error cuando el servicio no está disponible en entorno de desarrollo

### ISSUE THREAD

**Issue by icreaciones** [josemmo/Facturae-PHP#134]
Buenos días,

Si el entorno de desarrollo de face ( https://se-face-webservice.redsara.es/facturasspp2 ) no está disponible, como es el caso de ahora mismo día 27/07/2023 que devuelve un 503 Service Unavailable, obtenemos un error de loadXML ya que intentar procesar el XML de respuesta en lugar del XML del 503 y da un fallo. En cambio si apuntamos a producción, se procesa correctamente el XML de respuesta que da FACE con el ok o el error, pero en desarrollo salta un error al no saber procesar el XML del 503.

Pasa tanto en face como en faceb2b.

_Igualmente indicarte que en la documentación nombras la clase FaceB2bClient en camelCase, pero la clase la tienes en minúscula ;)_

<img width="1537" alt="Captura de pantalla 2023-07-27 a las 9 06 45" src="https://github.com/josemmo/Facturae-PHP/assets/97635999/aa9a525e-2c8a-4cec-94e7-d8f0ed364311">

<img width="1036" alt="Captura de pantalla 2023-07-27 a las 9 07 43" src="https://github.com/josemmo/Facturae-PHP/assets/97635999/fd37d34e-69ef-4977-b1cb-db64b8900f48">

Hemos puesto un formulario de contacto de face para notificar que la plataforma de desarrollo está caída...a ver si contestan algo...

Un saludo

**Comment by josemmo** [comment]
Hola @icreaciones,

> Igualmente indicarte que en la documentación nombras la clase FaceB2bClient en camelCase, pero la clase la tienes en minúscula ;)

Tomo nota, estará corregido en la siguiente release.

---

En cuanto al entorno de pruebas de Redsara, no se muy bien qué puedo hacer al respecto, yo solo mantengo la librería... 😅
Ahora mismo ya funcionan, cuando se caen no suele ser por mucho rato.
