### ISSUE TITLE
Error entorno de pruebas DIRe

### ISSUE THREAD

**Issue by BorjaMateo95** [josemmo/Facturae-PHP#138]
Hola buenas tardes,
En el entorno de pruebas de DIRe no me deja crear un directorio de entidad, me dice todo el rato que el NIF ya ha sido utilizado pero no me aparece ningún directorio de entidad y me vuelve a preguntar que si quiero crear un DIRe a ese NIF.
Esto me bloquea por completo, he puesto reclamación en 2 sitios y todavía nadie me lo ha resuelto.
Esto me ha pasado con 2 certificados de 2 clientes que me han prestado su certificado para probar en el entorno de pruebas.
a alguien mas le ha pasado algo parecido ?
hay otra manera de crear DIRE y FACEB2B para pruebas con un certificado de pruebas ?

Gracias
<img width="729" alt="error_lorca_test_dire_2" src="https://github.com/josemmo/Facturae-PHP/assets/44240440/41e7f75a-bdb3-44ce-8d5a-605febdafedc">

![error_lorca_test_dire](https://github.com/josemmo/Facturae-PHP/assets/44240440/0b33f23c-ad91-479f-8e12-fe9160fa73f2)

**Comment by josemmo** [comment]
Hola @BorjaMateo95,

El problema que comentas parece ser de DIRe y, lamentablemente, se escapa a mi control.

No se muy bien a qué refieres con que has puesto una reclamación en dos sitios, pero te recomiendo que crees una incidencia desde este enlace: https://sede.administracionespublicas.gob.es/ayuda/consulta/DIRE
