### ISSUE TITLE
Cambio de namespace

### ISSUE THREAD

**Issue by josemmo** [josemmo/Facturae-PHP#14]
Se abre este issue para discusión sobre el posible cambio del namespace de las facturas planteada por @alphp en #11. Actualmente el namespace se genera de la siguiente forma:

```php
$xmlns = 'xmlns:ds="http://www.w3.org/2000/09/xmldsig#" ' .
  'xmlns:etsi="http://uri.etsi.org/01903/v1.3.2#" ' .
  'xmlns:fe="http://www.facturae.es/Facturae/2014/v' .
  $this->version . '/Facturae"';
```

**Comment by alphp** [comment]
Efectivamente, hay varias formas, cada uno tiene sus manías y le resulta más caro verlo de una forma u otra.
En el #11 proponía esta:
```
$xmlns = null;
$xmlns .= 'xmlns:ds="http://www.w3.org/2000/09/xmldsig#" ';
$xmlns .= 'xmlns:xades="http://uri.xades.org/01903/v1.3.2#" ';
$xmlns .= 'xmlns:fe="http://www.facturae.es/Facturae/2014/v' . $this->version . '/Facturae"';
```
Pero también puede ser esta:
```
$xmlns[] = 'xmlns:ds="http://www.w3.org/2000/09/xmldsig#"';
$xmlns[] = 'xmlns:xades="http://uri.xades.org/01903/v1.3.2#"';
$xmlns[] = 'xmlns:fe="http://www.facturae.es/Facturae/2014/v' . $this->version . '/Facturae"';
$xmlns = implode(' ', $xmlns);
```
La primera forma es la que suelo preferir yo, me resulta más clara de leer y entender.
La segunda forma es la que suelo utilizar si las cadenas a concatenar puede varias o pretendemos que se puedan parametrizar.
Un saludo

**Comment by josemmo** [comment]
Hola @alphp,

Me refería al cambio de `xmlns:etsi="http://uri.etsi.org/01903/v1.3.2#"` por `xmlns:xades="http://uri.xades.org/01903/v1.3.2#"`.

**Comment by alphp** [comment]
Ups!!!, vale.
En realidad lo de utilizar el xades es por la documentación de FacturaE:
http://www.facturae.gob.es/formato/Paginas/politicas-firma-electronica.aspx

**Comment by josemmo** [comment]
¡Resuelto!

Se cambia el namespace de `etsi` a `xades` en el commit fddd1d0bb80d46388f3d8cd1d03da333e4f2270f

**Comment by alphp** [comment]
Por alguna razón cuando se cambia al namespace de etsi a xades la firma no valida.

**Comment by josemmo** [comment]
Cierto, *mea culpa*.

En la definición de los namespaces hay que declararlos en orden alfabético para que a la hora de validar los contenidos firmados éstos coincidan:

```
xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
xmlns:etsi="http://uri.etsi.org/01903/v1.3.2#"
xmlns:fe="http://www.facturae.es/Facturae/2014/v3.2.1/Facturae
```

pasa a ser

```
xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
xmlns:fe="http://www.facturae.es/Facturae/2014/v3.2.1/Facturae
xmlns:xades="http://uri.etsi.org/01903/v1.3.2#"
```
