### ISSUE TITLE
Pregunta: e.FACT

### ISSUE THREAD

**Issue by sixtemas** [josemmo/Facturae-PHP#141]
Disculpa mi ignorancia. 

¿Existe la posiblidad de enviar las facturas a EFACT? 

(Punto General de Facturas Electrónicas de Administraciones Públicas de Cataluña)

El equivalente a FACe en Cataluña.

Saludos

Jorge

**Comment by josemmo** [comment]
Hola @sixtemas,

No lo he probado, pero en principio deberías poder enviar facturas a e-FACT usando la clase `CustomFaceClient` y el siguiente endpoint:
```
https://efact.aoc.cat/bustia/services/EFactWebServiceProxyService
```

Tienes más información en la documentación de la librería: https://josemmo.github.io/Facturae-PHP/envio-y-recepcion/face.html#cliente-personalizado
