### ISSUE TITLE
Problemas validación con certificados camefirma

### ISSUE THREAD

**Issue by khernandeza1993** [josemmo/Facturae-PHP#142]
Hola José.

Pprimero que todo muchas gracias por este desarrollo, ¡Muy Completo!

Tengo un error que no he podido resolver. he implementado facturae-PHP y generado una factura con el certficado de la FNMT y face me valida la factura perfectamente. Sin embargo cuando genero otra factura con un el certificado de Camefirma me da problemas al validar y no he podido encontrar en donde se genere el bug.

He intentado muchas soluciones y no lo logro. De hecho genere la factura sin firmar y posteriormente firme con el programa "autofirma" y si me valido. No se si Camefirma tenga alguna validación adicional o algo que genere este error de validación.

Muchas gracias, te dejo el archivo zip con dos factura. la que se llama factura_correcta.xsig es el que firme con "autofirma" y el que dice factura_incorrecta.xsig es el que firme con tu libreria

[~factura electronica.zip~](#)

EDIT @josemmo: Eliminada factura por contener información personal

**Comment by khernandeza1993** [comment]
Me olvide mencionarte, que al parecer los certificados de Camefirma fallan en la libreria en el FacturaeSigner.php y con un pequeño fix pude solucionarlo. Lo que hice fue validar que dentro del foreach de $certData['issuer'] no hubiera otro array lo cual causaba index error. Te dejo el fix que aplique:

foreach ($certData['issuer'] as $item=>$value) {
      if (is_string($item) && is_string($value)) {
          // Agrega el elemento al array
          $certIssuer[] = "$item=$value";
      }
      else{
        foreach ($value as $key=>$value2) {
          $certIssuer[] = "$item=$value2";
        }
      }

    }

**Comment by josemmo** [comment]
Hola @khernandeza1993,

He eliminado el adjunto ya que se trataba de una factura real. Todo lo que se publica en este repo de GitHub es visible por cualquier usuario.

Marco el issue como bug para arreglarlo en la próxima release.
