### ISSUE TITLE
Múltiples facturas en el mismo export

### ISSUE THREAD

**Issue by cegara** [josemmo/Facturae-PHP#145]
Hola¡
Antes que nada, un grandísimo trabajo. Increíble la verdad. Gracias¡

Aunque no se si es el lugar correcto para expresar esto, hay algún plan de implementar las facturas múltiples?
De tal forma que puedan exportarse en un solo fichero xml/xsig varias facturas.

Saludos¡

**Comment by josemmo** [comment]
Hola @cegara,

No, la librería solo permite exportar una factura por documento XML.
Si te soy sincero, en los 6 años que llevo programando esto jamás he encontrado un documento de FacturaE con más de una factura (pese a que la especificación lo permite).

¿Por qué lo necesitas?

**Comment by cegara** [comment]
Hola¡¡

Pues la verdad es que se usa en una función que permite descargar varias facturas en formato facturae del mismo cliente.
ahora tiene que descargarse todas las facturas por separado.
Sería genial que pudiera descargarse todas las facturas en un solo fichero.

**Comment by josemmo** [comment]
Hola @cegara,

¿Pero dónde se usa? ¿Hay algún organismo público que lo soporte? Lo pregunto porque de nada sirve generar un fichero así si no es interoperable (si nadie más lo puede leer).

**Comment by josemmo** [comment]
Cerrado por inactividad.
