### ISSUE TITLE
PaymentsOnAccount

### ISSUE THREAD

**Issue by dypsysss** [josemmo/Facturae-PHP#146]
Hola, gran trabajo. Estoy muy agradecido.

No encuentro el apartado de Payments On Account del manual de facturae (https://www.facturae.gob.es/formato/Versiones/Esquema_castellano_v3_2_x_06_06_2017_unificado.pdf) el apartado 3.1.5.11 (pag.36) que hace referencia a Anticipos (Entrega a Cuenta) que se aplica a nivel de factura.

Muchas gracias por el trabajo realizado.

**Comment by josemmo** [comment]
Hola @dypsysss,

Eso es porque la librería no tiene implemebtados los anticipos.
Si encuentro un rato en estas fechas, probablemente lo implemente.
