### ISSUE TITLE
Firma invalida

### ISSUE THREAD

**Issue by oriolvinals** [josemmo/Facturae-PHP#147]
Hola Jose, 

Primero de todo, gracias por la librería. 

Estoy intentando firmar la factura, en un principio parece que la firma correctamente, pero cuando la valido en páginas de terceros (https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/validation, https://face.gob.es/es/facturas/validar-visualizar-facturas) me salta que no es correcta.

![image](https://github.com/josemmo/Facturae-PHP/assets/58267656/0719fe28-61c1-4a5f-a759-207290f90396)
![image](https://github.com/josemmo/Facturae-PHP/assets/58267656/32305999-b0a4-428d-9ac6-21fdd573f989)

He usado `Autofirma` para firmar también una factura y al parecer sí que ahí me la firma bien y me la acepta correctamente.

Adjunto los dos `.xsig` generados.

[firmas.zip](https://github.com/josemmo/Facturae-PHP/files/13940321/firmas.zip)

¡Espero que puedas arrojar algo de luz!

Muchas gracias.

**Comment by oriolvinals** [comment]
Añado que usando directamente el archivo `.p12/.pfx` ni me llega a signar la factura. Tengo que convertir ese archivo a clave pública y privada para que se añada correctamente el certificado a la factura.

He visto https://josemmo.github.io/Facturae-PHP/firma-electronica/#nota y no entiendo como añadir los certificados raíz en mi certificado. (He intentado añadir los certificados a la clave pública y aun asi seguía validando incorrectamente la factura).

Ya me he quedado sin ideas...

Muchas gracias. :)

**Comment by josemmo** [comment]
Hola @oriolvinals,

Parecen dos problemas distintos.

> He usado Autofirma para firmar también una factura y al parecer sí que ahí me la firma bien y me la acepta correctamente.
> Adjunto los dos .xsig generados.

¿Estás seguro de que estás usando Facturae-PHP? Porque ninguno de los dos XML que hay en el ZIP han sido firmados con esta librería (o si lo han sido, has sido modificados después).

> Añado que usando directamente el archivo .p12/.pfx ni me llega a signar la factura. Tengo que convertir ese archivo a clave pública y privada para que se añada correctamente el certificado a la factura.

¿Qué versión de PHP y de OpenSSL usas? Puedes verlo desde `php --info`.

**Comment by oriolvinals** [comment]
Hola @josemmo,

Si, una de las dos facturas ha sido usando la librería, el otro con Autofirma.

Estoy usando PHP 8.2 y OpenSSL 3. Investigando he encontrado que hay certificados que no los puede leer debido a que no hay el modo `legacy` activado. https://www.php.net/manual/en/function.openssl-pkcs12-read.php#128941

Fuera del proyecto donde quiero usar la libería he conseguido que funcione gracias a modificar el archivo `openssl.cnf`.

Así que creo que es cosa del proyecto/openssl y no de tu librería. Cierro la issue!

Muchas gracias.
