### ISSUE TITLE
Entorno de pruebas

### ISSUE THREAD

**Issue by fjsampe** [josemmo/Facturae-PHP#148]
¿Cómo saber si el entorno de pruebas está operativo? Esa es la duda.
Llevo varios días (4 en concreto) intentando realizar pruebas en FACE pero me devuelve un error 401 que no tiene mucho sentido ya que hasta ese día estaba funcionando todo correctamente y con el mismo certificado presento facturas en el entorno de pruebas de TBAI y me funcionan correctamente.

**Comment by josemmo** [comment]
Hola @fjsampe,

Desde esta semana, el entorno de pruebas de FACe y FACeB2B está caído porque fallan los tests automáticos que se hacen cada lunes: https://github.com/josemmo/Facturae-PHP/actions/runs/7695980928/job/21121953401

Puede que esté relacionado con que FACe ha desplegado unos nuevos webservices. Lamentablemente, hasta dentro de unas semanas no creo que tenga tiempo para echarle un ojo.

**Comment by josemmo** [comment]
Hola @fjsampe,

No ha cambiado nada de la implementación del webservice.

Al parece FACe ha desplegado una nueva versión de su web para proveedores, y ha resetado los datos que había hasta ahora. Hay que volver a subir el certificado que se quiera usar para comunicarse con el webservice en esta URL: https://se-proveedores-face.redsara.es/area-privada/certificados/listado
