### ISSUE TITLE
Comprobación documento extranjero

### ISSUE THREAD

**Issue by chusmsanchez** [josemmo/Facturae-PHP#149]
Hola buenos días!

Primero agradecer el desarrollo de la librería que os habéis trabajado, es excelente!!

Tengo una duda respecto al generar una factura-e.

Funciona todo correctamente si es para un cliente español con su documentación española tanto para persona fisica como persona jurídica, el problema lo tengo con lo siguiente:
- Facturo a un cliente italiano, que tiene el documento ITNNNNNNNNNN y cuando intento validar la factura con la plataforma de face me da error del DNI del receptor. ¿Como lo podemos solucionar?

Gracias de antemano!

**Comment by josemmo** [comment]
Hola @chusmsanchez,

Asumo que estás usando el campo "countryCode" que aparece mencionado en [la documentación](https://josemmo.github.io/Facturae-PHP/entidades/otros-paises.html).

¿Dónde estás intentando enviar la factura? ¿Qué código de error obtienes?

**Comment by soportebilltonic** [comment]
Hola sí, lo estoy usando, en este caso se envia ITA (Italia).

Lo que hago actualmente no es sincronizarlo con FACE, es generar el fichero *.xsig y cuando intento validar el fichero desde la plataforma de validar de FACE es cuando me salta el error de que el DNI del receptor no es válido.

Paso el código que uso:

`$buyer = new FacturaeParty([
		"isLegalEntity" => true,
		"taxNumber"     => $NifDni,
		"name"          => $NombreCliente,
		"firstSurname"  => $NombreCliente,
		"lastSurname"   => "",
		"address"       => $Direccion,
		"postCode"      => $CodPostal,
		"town"          => $Poblacion,
		"province"      => $Provincia,
		"countryCode"   => $PaisIso3Cliente,
		"email"         => $Email,
		"phone"         => $Tlf1,
	]);`

También los valores que obtengo en el xsig:

`<PersonTypeCode>J</PersonTypeCode>
<ResidenceTypeCode>U</ResidenceTypeCode>
<TaxIdentificationNumber>IT0345672013</TaxIdentificationNumber>
</TaxIdentification>
<LegalEntity>
<CorporateName>XXX</CorporateName>
<OverseasAddress>
<Address>XXXX</Address>
<PostCodeAndTown>XXXX</PostCodeAndTown>
<Province>XXX</Province>
<CountryCode>ITA</CountryCode>
</OverseasAddress>
....
`

**Comment by chusmsanchez** [comment]
Hola sí, lo estoy usando, en este caso se envia ITA (Italia).

Lo que hago actualmente no es sincronizarlo con FACE, es generar el fichero *.xsig y cuando intento validar el fichero desde la plataforma de validar de FACE es cuando me salta el error de que el DNI del receptor no es válido.

Paso el código que uso:

$buyer = new FacturaeParty([
		"isLegalEntity" => true,
		"taxNumber"     => $NifDni,
		"name"          => $NombreCliente,
		"firstSurname"  => $NombreCliente,
		"lastSurname"   => "",
		"address"       => $Direccion,
		"postCode"      => $CodPostal,
		"town"          => $Poblacion,
		"province"      => $Provincia,
		"countryCode"   => $PaisIso3Cliente,
		"email"         => $Email,
		"phone"         => $Tlf1,
	]);

También los valores que obtengo en el xsig:
< TaxIdentification >
< PersonTypeCode >J</ PersonTypeCode >
< ResidenceTypeCode >U</ ResidenceTypeCode >
< TaxIdentificationNumber >IT0345672013</ TaxIdentificationNumber >
</ TaxIdentification >
< LegalEntity >
< CorporateName >XXX</ CorporateName>
< OverseasAddress>
< Address>XXXX</ Address>
< PostCodeAndTown>XXXX</ PostCodeAndTown>
< Province>XXX</ Province>
< CountryCode>ITA</ CountryCode>
</ OverseasAddress>
....

**Comment by josemmo** [comment]
Hola @chusmsanchez,

FACe está pensado para remitir facturas a las AA.PP. españolas. Ya que el comprador (`$buyer`) de tu factura es una persona física de nacionalidad italiana, es normal que no pase la validación.

**Comment by chusmsanchez** [comment]
Ok, muchas gracias por la aclaración.

Otra cosa que mne gustaría añadir: te escribí personalmente por el chat de twitter haciendo una pregunta si tenéis pensado desarrollar alguna libreria para verifactu ya que es lo próximo que va a salir relacionado con los software de facturación.

Si es afirmativo, me gustaría que podamos hablar y nosotros también poder ayudaros todo lo que podamos ya que consideramos que si hacemos uso de las librerias también nos gusta aportar nuestro granito de arena.


Saludos.

**Comment by josemmo** [comment]
Todavía no tengo claro si voy a desarrollar una librería para VeriFactu por temas de tiempo. Si al final me decido a ello, seguramente lo publique aquí.

**Comment by chusmsanchez** [comment]
Ok entendido, si te decides y podemos aportar no dudes en contactarme. Aportariamos ya sea bien con tiempo, conocimientos o económicamente si fuese necesario.

Saludos.
