### ISSUE TITLE
Ley aplicable 1007/2023

### ISSUE THREAD

**Issue by dcraig9123** [josemmo/Facturae-PHP#153]
Buenas! Muchas gracias por tu trabajo, se agradece.

Mi pregunta es si la librería ya está adaptada al último decreto 1007/2023 que entrará en vigor a partir del 1 de julio de 2025: https://www.boe.es/buscar/act.php?id=BOE-A-2023-24840 o si es necesario realizar alguna modificación.

De nuevo, gracias.

**Comment by josemmo** [comment]
Hola @dcraig9123,

El RD 1007/2023 no afecta a FacturaE, VeriFactu es una obligación tributaria a parte. FacturaE seguirá existiendo como formato para emitir facturas a la Administración Pública.
