### ISSUE TITLE
SOAP-ENV:ServerProcedure 'consultarFactura' not present

### ISSUE THREAD

**Issue by DRenginyer** [josemmo/Facturae-PHP#155]
el metodo de consultar factura, no esta funcionando, supongo que estan migrando los servicios SOAP a los nuevos servicios y algunos ya dejan de funcionar. Esta previsto la migración a los nuevos servicios? gracias!

**Comment by josemmo** [comment]
Hola @DRenginyer,

Con "no funciona", ¿te refieres a que te devuelve algún error concreto? Los webservices originales siguen funcionando sin problemas: https://github.com/josemmo/Facturae-PHP/actions/runs/8867410054/job/24666205839

Con tan poca información, lo único que te puedo recomendar es que pruebes la rama "develop" de la librería:
```
composer require josemmo/facturae-php:dev-develop
```

**Comment by DRenginyer** [comment]
disculpa jose, el error que devuelve es : SOAP-ENV:ServerProcedure 'consultarFactura' not present , provare lo que dices, muchas gracias!!!!

**Comment by DRenginyer** [comment]
mas info : Para subir las facturas solo me funciona este endpoint "https://se-ws-face.redsara.es/proveedores/v1/factura" (el "nuevo" entorno de pruebas) , el endpoint "antiguo" "https://se-face-webservice.redsara.es/facturasspp2" siempre me rechaza las facturas.
Ahora bien, en el endpoint antiguo funciona correctamente la funcion consultarFactura, pero en el endpoint nuevo da el error SOAP-ENV:ServerProcedure 'consultarFactura' not present. Teoricamente el endpoint nuevo deberia ser retrocompatible (asi me lo dijeron en consultas que hice al face...), todo parece indicar que han migrado algun servicio... y otros no...

**Comment by josemmo** [comment]
Pues no sabría decirte. Los tests de webservices se han ejecutado esta mañana en el endpoint que llamas "antiguo" y se ha podido registrar la factura correctamente en FACe. En [esta clase](https://github.com/josemmo/Facturae-PHP/blob/52d4bf624bb1e65085164f67ded349ea583ad898/tests/WebservicesTest.php#L51) tienes el código fuente que se ha ejecutado.

¿Seguro que estás usando la clase `FaceClient` de esta librería? ¿Puedes pasar el código que estás usando para enviar la factura para poder diagnosticar el fallo?

**Comment by DRenginyer** [comment]
si, uso la clase FaceClient identicamente que tu codigo, la unica diferencia es la firma, genero el XML y lo mando al navegador para ser firmado con autofirma, y luego subo ese XML firmado. Lo raro es que en un endpoint funcione y en otro no, el mismo codigo... Decir tambien, que el usuario que tenia de pruebas en el endpoint antiguo, me lo borraron, y me tuve que dar de alta de nuevo, y segun Face, ya solo se da de alta en la version nueva de pruebas, aunque tambien dicen que los servicios con retrocompatibles... en fin ... un lio importante... seguire investigando, muchas gracias por tu ayuda y paciencia ! un gran trabajo!
