### ISSUE TITLE
Error en la documentacion para cargar la libreria sin composer

### ISSUE THREAD

**Issue by Juliogarridovico** [josemmo/Facturae-PHP#162]
buen dia y gran trabajo

Estoy revisando la librería para un proyecto y en la documentación, en el apartado "Uso sin Composer", se indica que las librerías deben cargarse de la siguiente manera:

require_once 'ruta/hacia/Facturae-PHP/src/Common/FacturaeSigner.php';
require_once 'ruta/hacia/Facturae-PHP/src/Common/KeyPairReaderTrait.php';
require_once 'ruta/hacia/Facturae-PHP/src/Common/XmlTools.php';
require_once 'ruta/hacia/Facturae-PHP/src/FacturaeTraits/PropertiesTrait.php';
require_once 'ruta/hacia/Facturae-PHP/src/FacturaeTraits/UtilsTrait.php';
require_once 'ruta/hacia/Facturae-PHP/src/FacturaeTraits/SignableTrait.php';
require_once 'ruta/hacia/Facturae-PHP/src/FacturaeTraits/ExportableTrait.php';
require_once 'ruta/hacia/Facturae-PHP/src/Facturae.php';
require_once 'ruta/hacia/Facturae-PHP/src/FacturaeCentre.php';
require_once 'ruta/hacia/Facturae-PHP/src/FacturaeItem.php';
require_once 'ruta/hacia/Facturae-PHP/src/FacturaeParty.php';

En mi caso, aparece el siguiente error:

Fatal error: Trait 'josemmo\Facturae\Common\KeyPairReaderTrait' not found in C:\xampp\htdocs\sii\includes\facturae\Common\FacturaeSigner.php on line 10

Estoy usando XAMPP con la versión de PHP 7.4.33, y también he probado con PHP 8. La solución ha sido simplemente cambiar el orden de los require. Al mover el require_once 'ruta/hacia/Facturae-PHP/src/Common/FacturaeSigner.php'; al final de los includes, el error desaparece y las facturas se crean y se firman correctamente.

**Comment by dixitalmedia** [comment]
@Juliogarridovico no sé si estará relacionado con un caso que había comentado hace tiempo https://github.com/josemmo/Facturae-PHP/issues/115
O quizás te dé una pista para descubrir el error
