### ISSUE TITLE
VeriFactu

### ISSUE THREAD

**Issue by Pinazinho** [josemmo/Facturae-PHP#163]
Hola, esto sirve para implantar el VeriFactu?

**Comment by josemmo** [comment]
Hola @Pinazinho,

No, VeriFactu es otra ley distinta, FacturaE se sigue aplicando igual.

Duplicado de #153.

**Comment by Pinazinho** [comment]
Pero sabes si hay alguna API para desarrollar lo que se solicita en
Verifactu y conectarse con Hacienda?

**Comment by josemmo** [comment]
Hasta donde yo se, no. Es más, ni el webservice oficial de la AEAT está operativo, y eso que la ley ya ha entrado en vigor.
