### ISSUE TITLE
`serialNumber` es demasiado largo y viene como hexadecimal

### ISSUE THREAD

**Issue by PaolaRuby** [josemmo/Facturae-PHP#164]

**Comment by josemmo** [comment]
Hola @PaolaRuby,

¿Puedes pasar el certificado con el que ocurre el fallo?

**Comment by PaolaRuby** [comment]
Lamentablemente como todos los problemas anteriores, la firma es de un cliente, y por confidencialidad no la puedo enviar
De todas formas mi problema esta solucionado, solo lo comente para que tengan en cuenta la solución si le ocurre a alguien

Si te sirve el hexadecimal fue `0x63C31426D0557EB712705F05CC62A80B64CB471F` y con esta funcion queda `569540487078645501056583593785013956447969167135`

**Comment by josemmo** [comment]
Hola @PaolaRuby,

Me parece un poco feo que crees un issue para avisar de un supuesto fallo, no menciones **ni siquiera cómo reproducirlo**, ni qué mensaje de error aparece, ni por qué es un fallo, y como solución propongas un código incomprensible sacado por ChatGPT.

Entiendo la parte de confidencialidad, pero ¿no podrías al menos molestarte en explicar el fallo o en proporcionar un certificado de prueba sin datos confidenciales para que altruistamente pueda venir yo a arreglarlo? Ya que no pido dinero a tu empresa por usar mi librería, y que la licencia os permite cobrar a vuestros clientes por usarla, me parece lo mínimo.

**Comment by PaolaRuby** [comment]
>ni qué mensaje de error aparece

el Servicio de Rentas Internas solo dice `firma invalida` ese mensaje no dice nada,
usando JAVA con un XSD de xades encontre `serialNumber must be integer`

>propongas un código incomprensible sacado por ChatGPT

No se xq incomprensible, el nombre de la función prácticamente lo explica, `hexToDecManual` **hexadecimal a decimal manualmente**, aparentemente ChatGPT nombra los metodos por lo que hacen, 
ademas `bcadd` y `bcmul` aparentemente estan documentados en [BC Math](https://www.php.net/manual/es/ref.bc.php#ref.bc), solo que le pedi que no use ninguna libreria, solo PHP puro, por lo que puso los metodos manualmente, lo deduje al leer un poco
https://www.php.net/manual/es/function.bcadd.php
https://www.php.net/manual/es/function.bcmul.php

>ni por qué es un fallo

Lo siento, pense que sabrias mas de este tema que mi, solo egrese hace poco y estoy deduciendo todo,  `serialNumber` al parecer como dice el tag, solo puede ser numeros, no letras, y al ser hexadecimal vienen letras y se produce el fallo

>proporcionar un certificado de prueba sin datos confidenciales

Ni idea como hacer eso, se que las firmas las compran a una certificadora, no tengo contacto con nadie de ahi, parece q escuche que llenan un formulario online, pagan y llega el archivo P12 al email, estoy en lo mas bajo de la cadena, son practicas pre profesionales, no se si en España haran eso, son pasantias no remuneradas por la experiencia que debes hacer antes de sacar el titulo

>Ya que no pido dinero a tu empresa por usar mi librería

Estamos en otro pais, no usan tu codigo, pero algunas partes se parecen en el Xades, talvez fue una version inicial tuya, o talvez se guiaron y copiaron partes para adaptar el Xades a como se usa aca, ni idea, llegue hace poco y esto esta funcionando
Bueno lo corrijas o no en tu codigo en realidad no me afecta a mi, ni a la empresa en la que estoy, solo comunicaba porque me gusta el open source, y es feo perder el tiempo sin encontrar nada en internet y te presionen q debes buscar solución a un código que ni entiendes, en esto de openssl me esta pasando

>Me parece un poco feo que crees un issue para avisar de un supuesto fallo

Yo pense que era normal crear issues para avisar fallos, siempre que creo un issue me aseguro de postear tambien la solucion para ayudar al autor y que no pierda valioso tiempo, pero no volvera a pasar, tienes mi palabra

**Comment by PaolaRuby** [comment]
Y no tiene nada de malo ser altruista
https://bugs.php.net/bug.php?id=77411

**Comment by cesarreyes3** [comment]
Hay muchos ejemplos de esto en internet, la respuesta de ChatGpt es correcta y me parece entendible
Hay q tener tino para comunicarse con españoles 😄, ya se sabe como son

**Cert. Ejemplo:** [https://github.com/php/php-src/pull/6445/files](https://github.com/php/php-src/pull/6445/files#diff-a703d4266c391ef5ca0278d1b47793976080b01f16e4c27482c3cf1b7d42d385)
**Test:** https://paiza.io/projects/e/hdpsjSoQ-Oo5ALgJawctqw
