### ISSUE TITLE
Aplicar descuentos generales de manera secuencial

### ISSUE THREAD

**Issue by jordi-n-tropia** [josemmo/Facturae-PHP#165]
Hola @josemmo,

Te escribo en relación con la librería Facturae-PHP.

Debido a requerimientos del cliente, estoy tratando de crear una factura con varios descuentos generales que deben aplicarse de manera secuencial. 

Te muestro un ejemplo para clarificarlo. En este caso aplico tres descuentos generales del 50% uno tras otro sobre el total:

- Total: 10000 EUR

- Descuento 1: 50% => 5000 EUR
- Descuento 2: 50% => 2500 EUR
- Descuento 3: 50% => 1250 EUR

por lo tanto el total de descuentos es de 8750 EUR.

He intentado implementar esto usando el método addDiscount(), pero no estoy seguro de si la librería soporta la aplicación de descuentos de manera secuencial de esta forma ya que parece ser que los aplica sobre el total de la factura uno tras otro es decir,

- Descuento 1 me retorna 5000 EUR, 
- Descuento 2 me retorna 5000 EUR,
- Descuento 3 me retorna 5000 EUR,

por lo tanto el total de descuentos es de 15000 EUR.

¿Podrías decirme si hay alguna opción que no he visto de la librería para poder realizar esto? ¿Es posible realizarlo?

Muchas gracias,

Jordi Trigo

**Comment by josemmo** [comment]
Hola @jordi-n-tropia,

No es posible hacer lo que comentas en la librería.

Lo he estado echando un ojo y creo que tampoco es posible implementarlo ya que, según la [especificación de FacturaE](https://www.facturae.gob.es/formato/Versiones/Esquema_castellano_v3_2_x_06_06_2017_unificado.pdf), los `<GeneralDiscount />` siempre se deben aplicar sobre el Total Importe Bruto (TIB).

**Comment by jordi-n-tropia** [comment]
Hola @josemmo,

muchas gracias por tomarte el tiempo de revisarlo y por la aclaración. Por lo que veo, así es como debe ser aplicado.

Recibe un cordial saludo.
