### ISSUE TITLE
Factura simple

### ISSUE THREAD

**Issue by MiBasDev** [josemmo/Facturae-PHP#166]
Como se supone que generas una factura simplificada? Hay que pedir sí o sí el NIF o hay algún genérico que se pueda usar?

**Comment by josemmo** [comment]
Hola @MiBasDev,

Pues no te sabría decir, esto es más un problema fiscal/legal que técnico... 😅

Según la [especificación de FacturaE](https://www.facturae.gob.es/formato/Versiones/Esquema_castellano_v3_2_x_06_06_2017_unificado.pdf), el campo `<TaxIdentificationNumber />` (CIF o NIF) es siempre obligatorio, independientemente del tipo de documento. No me suena que exista un valor genérico que puedas usar para estos casos.

Ya solo por curiosidad, ¿para qué caso de uso necesitas emitir una facturae simplificada en formato FacturaE?

**Comment by MiBasDev** [comment]
Estamos desarrollando un plugin para woocomerce y es comun que en las ventas haya clientes que no ponen el NIF o lo ponen pero son extranjeros con dirección de España (turistas) y ambos casos da error a la hora de validar la facturae.
No se si la ley dice que es solo entre empresas españolas, en ese caso se nos reduce el numero de facturas.
¿Deberiamos excluir a particulares que el NIF sea correcto?

**Comment by dixitalmedia** [comment]
Hola @josemmo 

La antigua página de validación de la factura (que ahora ya no existe) validaba las facturas donde _ResidenceTypeCode_ tenía el valor U y el NIF era un VAT-ID de una empresa francesa, por ejemplo. 
Incluso habíamos previsto en los ajustes del plugin unos datos genéricos Nombre (Contado), CP (36200) y NIF (00000000T) que era lo mínimo que pedía para validar una venta con _ResidenceTypeCode_ R. Así el admin de la web fijaba esos valores por defecto para las compras hechas sin datos de cliente.
Ahora en el validador de Face no valida ni un caso ni otro.
Lo mismo para un _ResidenceTypeCode_ E que obviamente es imposible verificar (de todo el mundo).
Mismo error en todos de DNI incorrecto.
Podemos entender el segundo, ya que no existe. Pero una factura intracomunitaria con un documento real de una empresa europea o una extranjera tampoco.
¿Qué sentido tiene validar el NIF de factura emitida a un cliente de Kazajistán?

En cuanto al _InvoiceDocumentType_ si es FA se supone que no hay _BuyerParty_ como puede ser el caso de cliente que compra unos zapatos y no da su NIF, si se espera.

Lo bueno sería tenía facturas de ejemplo para los casos de intracomunitaria, extranjero y una simplificada. Y ver si es que dependen de otros campos además de _ResidenceTypeCode_ y/o _InvoiceDocumentType_.

Conclusión a la que hemos llegado: emitir solo factura-e si el _TaxIdentificationNumber_ del _BuyerParty_ se valida como NIF español, ya sea el _PersonTypeCode_ J o F porque podría ser un empresario autónomo.
En todos los demás casos solo emitimos factura PDF.

Coincidimos contigo en lo que dices "por qué un particular necesita una FacturaE".
Como a los particulares (caso de cliente sin NIF) no hay que emitirles factura-e y una empresa de fuera de España poco puede hacer mucho con ella que en sus países habrá otro formato, pues haremos así.

Lo que no entendemos es porque contemplan los supuestos de factura simplificada o a otros países si no se pueden validar.

Saludos
