### ISSUE TITLE
Compatibilidad con nueva normativa VERI*FACTU

### ISSUE THREAD

**Issue by kapsule** [josemmo/Facturae-PHP#167]
Hola,

Sabéis si esta librería es compatible con la nueva normativa que saldrá en breve sobre VERI*FACTU?

Gracias

**Comment by josemmo** [comment]
Hola @kapsule,

Veri*Factu no aplica a FacturaE, duplicado de #153.

**Comment by kapsule** [comment]
Muchas gracias por el feedback. Sabes si hay algún repo para el tema de verifactu? Gracias

**Comment by josemmo** [comment]
Lo siento, no estoy muy enterado :/
