### ISSUE TITLE
Añadir anticipo de cliente

### ISSUE THREAD

**Issue by aresof** [josemmo/Facturae-PHP#168]
Hola, me preguntaba si hay alguna forma de insertar el anticipo que nos hace un cliente en la factura o ese campo no está contemplado en la normativa de la factura electrónica.

Un anticipo es una entrega a cuenta que nos hace un cliente para ir abonando los suplidos que van surgiendo. Al final del trámite se hace una liquidación, donde se paga el sobrante o se cobra el faltante, según sea el caso.

Gracias por este magnífico trabajo que has realizado con esta librería.

**Comment by josemmo** [comment]
Hola @aresof,

Los anticipos están contemplados dentro de la especificación como el nodo `<PaymentsOnAccount />`. Sin embargo, esta funcionalidad no está implementada en la librería.
