### ISSUE TITLE
Error 100 al consultar estado de factura en FACe

### ISSUE THREAD

**Issue by antoniofr1982** [josemmo/Facturae-PHP#169]
Hola. He migrado a un nuevo servidor y he subido la versión de PHP desde la 7.4.33 a la 8.3. Antes todo funcionaba bien, pero ahora, al consultar el estado de una factura en FACe, me devuelve este error:

` SimpleXMLElement Object (
            [codigo] => 100,
            [descripcion] => La firma de la petición SOAP no es válida,
            [codigoSeguimiento] => 66f2a376af21c
        )`

¿Alguna idea?

Gracias

**Comment by joebordes** [comment]
solo por si ayuda: ¿puede ser que no tengas la extensión PHP SOAP instalada en el nuevo servidor?

**Comment by antoniofr1982** [comment]
La extensión php-soap la tengo instalada. Me da que el problema está relacionado con openssl. Mañana lo intentaré depurar a ver si averiguo cuál es el problema.

**Comment by josemmo** [comment]
Hola @antoniofr1982,

Facturae-PHP no necesita la extensión `php-soap`. El problema que comentas muy probablemente se deba a que tienes instalada una versión obsoleta de OpenSSL.

Puedes comprobar la versión de OpenSSL con este comando:
```sh
 php -r "echo OPENSSL_VERSION_TEXT;"
```

**Comment by antoniofr1982** [comment]
Hola.

Efectivamente es lo que comentas, no sé si no quedó claro en mi mensaje anterior.

Lo que había ocurrido es que el certificado P12 utilizado había sido generado con OpenSSL v1, pero al migrar de PHP 7.4 a PHP 8.3, esa versión de OpenSSL ya había sido declarada obsoleta. La solución fue volver a generar el certificado P12, pero con OpenSSL v3.

Muchas gracias.
