### ISSUE TITLE
Factura a ayuntamientos

### ISSUE THREAD

**Issue by martinlaregina** [josemmo/Facturae-PHP#17]
Hola José,

Te felicito por el proyecto. Me parece que tienes un error en el fichero FacturaeParty.php en la línea 73 al final de la línea es un ";" y no un "." ya concatena lo anterior con lo nuevo y genera un XML inválido.

Muchas gracias,

**Comment by josemmo** [comment]
Cierto. Muy buena cazada!

Añadiré pruebas al PHPUnit de `FacturaeParty` para que no vuelva a pasar.
