### ISSUE TITLE
Consulta nueva normativa 2025

### ISSUE THREAD

**Issue by kapsule** [josemmo/Facturae-PHP#170]
Hola. Me gustaría saber si esta librería es compatible con la nueva normativa que será obligatoria en 2025.

https://gb-consultores.es/nuevas-obligaciones-para-emitir-facturas-a-partir-de-2025/

**Comment by NeoRazorX** [comment]
Hola, no, la nueva normativa es verificar-factu, no es facturae.

@josemmo recomiendo poner alguna de estas issues anclada o bien poner un archivo de plantilla de issue, así evitarás tener que contestar a esta pregunta cada semana.

Aquí tienes un archivo de ejemplo:
- https://github.com/NeoRazorX/facturascripts/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by kapsule** [comment]
Ostras!!! muchas gracias @NeoRazorX por la información y disculpar el mensaje. Todo aclarado.

**Comment by kapsule** [comment]
Por cierto @NeoRazorX. Sabes si hay algún repositorio de PHP con una librería compatible para la nueva normativa? Gracias
