### ISSUE TITLE
Añadir campo TradeName en SellerParty

### ISSUE THREAD

**Issue by egrueda** [josemmo/Facturae-PHP#171]
Sería muy práctico añadir el campo TradeName (Nombre Comercial).
Así al visualizar la factura, el cliente puede reconocer fácilmente al emisor.

```
Esquema: 1.4.2.1.2.
Nombre: TradeName
Descripción: Nombre Comercial
Obl.: [0..1]
Tipo: TextMax40Type string positions: 0-40
```

![image](https://github.com/user-attachments/assets/a55f83d1-073e-4e2c-8c33-bafeb0a2f260)

**Comment by josemmo** [comment]
Hola @egrueda,

He añadido tus cambios de #172 a `develop` en 29ef62f5cdb938ce8c45eb6a1668efea2dd384b8.
