### ISSUE TITLE
Certificado representante

### ISSUE THREAD

**Issue by jgj1988-1** [josemmo/Facturae-PHP#173]
Buenas tardes. Antes de pedir ayuda, elogiarte por esta librería, has hecho un trabajo enorme, gracias de ante mano. Mi problema es que con el certificado de representante me dice que la firma no es válida o no está soportada, sin embargo sin tocar nada más que la contraseña y cambiar el certificado por el certificado personal funciona perfecto. No he visto tampoco nada en relación a esto en la ayuda/manual. espero que me puedas ayudar.
Gracias

**Comment by jgj1988-1** [comment]
Hola.
Uso xampp con php 8.2 y OpenSSL 3.1.3, lo acabo de actualizar tenía una versión antigua, y también me da error. 
El archivo XML lo genera, pero al abrirlo no lo reconoce. (te paso foto), sin embargo con certificado de persona física si (te paso foto también)
![con personal](https://github.com/user-attachments/assets/d88bd45d-3f06-439f-93cc-5c94d5de970d)
![con cert representante](https://github.com/user-attachments/assets/bb05b1ab-b1f2-4b36-97d6-bd3d7ee58b5f)

El caso es que necesito firmarlo con el certificado de representante de empresa, el certificado se expide a mi nombre se firma con mi nombre pero queda reflejada la empresa de la que soy dueño. He probado el mismo código, solamente cambio el p12 y contraseña. Seguramente se me ha pasado cambiar algo de la clase, al no  ser persona física y ser representante de X no doy con ello. Muchas gracias de antemano. 
    $xmlFactura=new Facturae();
    $xmlFactura->setPrecision(Facturae::PRECISION_INVOICE);
    switch($DatoPedido['Estado']){
        case 'P':{$xmlFactura->addPayment(new FacturaePayment(["method" => FacturaePayment::TYPE_CASH]));break;}
        case 'T':{$xmlFactura->addPayment(new FacturaePayment(["method" => FacturaePayment::TYPE_CARD]));break;}
        default :{$xmlFactura->addPayment(new FacturaePayment(["method"=>FacturaePayment::TYPE_TRANSFER,"iban"=>"ESxxxxxxxxxxxxxxx","dueDate" => strtotime('+30 day',strtotime(date('Y-m-d')))]));}

    }
    $xmlFactura->addLegalLiteral("LPI incluido en el precio de los productos sujetos a dicha tasa según RD-Ley 12/2017 de 3 de Julio.");
    $xmlFactura->setNumber('', $DatoPedido['IdPedido']);
    $xmlFactura->setIssueDate($DatoPedido['Fecha']);
    $xmlFactura->setSeller(new FacturaeParty(new FacturaeParty([
      "taxNumber" => "$strCIF",
      "name"      => "$strEmpresa",
      "address"   => "$strDirecion",
      "postCode"  => "$strCP",
      "town"      => "$strLocalidad",
      "province"  => "$strProvincia"
    ])));
    $xmlFactura->setBuyer(new FacturaeParty([
      "isLegalEntity" => false,       // Importante!
      "taxNumber"     => "$DatoPedido[DNI]",
      "name"          => "$DatoPedido[Cliente]",
      "address"       => "$DatoPedido[Direccion]",
      "postCode"      => "$DatoPedido[CP]",
      "town"          => "$DatoPedido[Localidad]",
      "province"      => "$DatoPedido[Provincia]"
    ]));

    mysqli_data_seek($resultProductosPedido,0);
    while($fila=$resultProductosPedido->fetch_array(MYSQLI_ASSOC)){
             $xmlFactura->addItem(new FacturaeItem(["name" =>$fila['Producto'],"unitPrice" =>$fila['Precio']+$fila['CanonDigital2017'],"quantity" =>$fila['Unidades'],"taxes" => [Facturae::TAX_IVA => 21]]));
    }
    $xmlFactura->addDiscount('',$DatoPedido['Descuento']*(1-$intIva/100),false);
    $xmlFactura->sign("../php/clases/firma.p12",null,"xxxxxxx");
    $xmlFactura->export("../pedidosxsig/FACT-N".$DatoPedido['IdPedido'].".xsig");

**Comment by jgj1988-1** [comment]
Lo acabo de solucionar, fantasmas de la informática. He instalado el mismo certificado que he usado en windows, lo he vuelto a exportar junto con la clave privada y extensión pfx y funciona correctamente. No entiendo nada, ambos certificado que usaba eran los dos archivos originales de la fmnt y extensión p12, uno funciona pero el otro no. Tendrá algo que ver la extensión p12 y al ser un certificado de representante de empresa??
Bueno gracias de todas formas, si lo quieres investigar...

**Comment by josemmo** [comment]
Gracias por avisar, @jgj1988-1. Me alegro de que esté solucionado!
