### ISSUE TITLE
 Deprecated (8192) : htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated en XmlTools.php

### ISSUE THREAD

**Issue by Lurtz963** [josemmo/Facturae-PHP#179]
Hola, 
he observado que en php 8.1 salta este warning,
Un saludo y gracias.

**Comment by josemmo** [comment]
Hola @Lurtz963,

En algún momento estás pasando un `NULL` a algún campo de Facturae-PHP que no lo admite. ¿Tienes el código fuente con el que generas la factura?

**Comment by Lurtz963** [comment]
Hola, gracias por la respuesta, ya he encontrado el error. me faltaba el número de referencia xD
Un saludo.
