### ISSUE TITLE
Consulta de DigestValue

### ISSUE THREAD

**Issue by luisbp** [josemmo/Facturae-PHP#18]
Saludos, una consulta el digest value que está en el sign policy 3_1, que elementos se procesan para obtener ese valor?

Gracias,

**Comment by josemmo** [comment]
Existen múltiples elementos `<ds:DigestValue/>` en la firma de la factura. ¿A cuál de ellos te refieres?

Sea cual sea, todo lo relativo al firmado está en el método `injectSignature` de `/Facturae.php`.

**Comment by luisbp** [comment]
Gracias, preguntaba por el que esta junto con el name y el url del sign policy, es este: "Ohixl6upD6av8N7pEvDABhEL6hM=" que está ya generado y no es procesado dentro del inject, si no que únicamente se incluye, pero quería saber de donde proviene ese valor...

De antemano gracias!

**Comment by josemmo** [comment]
Ah, el digest que mencionas lo especifica la política de firma v3.1 [en este documento](https://administracionelectronica.gob.es/ctt/resources/Soluciones/239/Area%20descargas/GuiaRapida-Politica-Firma-AGE-v1-8.pdf).
Desconozco de dónde se obtiene su valor.

**Comment by luisbp** [comment]
Muchas gracias! Saludos.
