### ISSUE TITLE
Subir las facturas a FACe

### ISSUE THREAD

**Issue by alphp** [josemmo/Facturae-PHP#21]
Hola, tengo resuelto el tema de subir las facturas a FACe:
https://github.com/fawno/Facturae

**Comment by josemmo** [comment]
Para añadir una funcionalidad a Facturae-PHP haz un *pull request* a la rama `develop`.

**Comment by alphp** [comment]
Mi proyecto es distinto y ahora no tengo tiempo de hacer un pull request al tuyo.
Sin embargo la funcionalidad de subir las facturas a FACe la tengo encapsulada en una clase y no es demasiado difícil añadirla a cualquier proyecto:
https://github.com/fawno/Facturae/blob/master/docs/wsdlFACe.md

**Comment by josemmo** [comment]
De acuerdo, no entendía el motivo del issue.

Lo doy por cerrado.
