### ISSUE TITLE
Redondeo de decimales

### ISSUE THREAD

**Issue by josemmo** [josemmo/Facturae-PHP#24]
Dado que FacturaE 3.2.X solo permite usar dos decimales, se presenta un problema adicional al ya solventado #23: el redondeo.

Más que un bug, esto es un problema de diseño importante que plantea una nueva incógnita: dado que hay que perder precisión a la fuerza porque lo exige el Estado, ¿es mejor que Facturae-PHP **obligue al usuario** a hacer facturas con decimales precisos (lanzando, por ejemplo, una excepción si el redondeo no es correcto), o que **ajuste automáticamente los importes** resultantes para que coincida con el total?

Esta es una factura de ejemplo en la que ocurre el problema del redondeo:
![Ejemplo](https://i.imgur.com/xTx65Do.png)

**Comment by NeoRazorX** [comment]
Hola, creo que una excepción ayudaría a la gente a realizar bien los cálculos, mientras que corregir los decimales puede llevar a situaciones donde el programador/usuario no se dé cuenta de que los totales no son los mismos.
