### ISSUE TITLE
Facturas a organismos públicos

### ISSUE THREAD

**Issue by sandraalgans** [josemmo/Facturae-PHP#29]
Hola @josemmo, 
primero de todo, gracias por tu trabajo!

He visto que cuando se genera el XML referente a la parte de los centros administrativos de un organismo público, no se está teniendo en cuenta los campos de la dirección del centro (address, postcode, town, province y countrycode), aunque el centro te permite especificar una información distinta para cada uno. Esto se encuentra en la función getXML de la clase FacturaeParty.php.

Muchas gracias!

**Comment by josemmo** [comment]
Hola @sandraalgans,

Muchas gracias por avisar.
Efectivamente, se trata de un fallo que ignora esos campos del `FacturaeCentre`.

Ya he publicado un commit en la rama *develop* y en cuanto acabe las pruebas lo paso a *master* y lanzo una nueva versión.

Un saludo!
