### ISSUE TITLE
Problema al calcular el total de la factura cuando hay varios impuestos

### ISSUE THREAD

**Issue by NeoRazorX** [josemmo/Facturae-PHP#31]
Hola, estoy probando tu librería para sustituir a la mía en la generación de facturae en FacturaScripts.

El caso es que yo genero miles de facturas con datos aleatorios para encontrar fallos, y me he encontrado que con las facturas con IRPF falla la validación contable.

`El fichero seleccionado no es validable: Error en su lectura: Totalfactura de la factura número 1 no es igual a TotalImporteBrutoAntesImpuestos + TotalImpuestosRepercutidos - TotalImpuestosRetenidos, debería ser : 618.37`

Mirando un poco más detenidamente veo que tu librería calcula incorrectamente el total y le baila un céntimo, dando como resultado 618.38

Ta adjunto el xml.
[FAC2018IR1_facturae.zip](https://github.com/josemmo/Facturae-PHP/files/2319526/FAC2018IR1_facturae.zip)

Mañana seguiré revisando. Y disculpa por si al final fuese problema mio ;-)

**Comment by josemmo** [comment]
He cambiado la forma en la que se redondean los importes de las facturas. En vez de calcular los totales y luego redondear, **ahora se redondean los importes de cada línea** y luego se suman para obtener los totales.

Es inevitable que con varios decimales se arrestre un pequeño error y el total de la factura difiera en uno o dos céntimos del esperado, pero al menos ahora la factura será válida.

Prueba a ver si te da problemas y me cuentas :wink:

**Comment by josemmo** [comment]
Cierro al issue por falta de actividad y al considerarlo resuelto en el commit 983262bfee71bec188e275d780fdacea8e793fca
