### ISSUE TITLE
descuento por linea de detalle

### ISSUE THREAD

**Issue by jboscosimj** [josemmo/Facturae-PHP#35]
Muy buenas Jose, ¿tienes algo desarrollado por el descuento por linea en los detalles de las facturas?

Gracias ante todo.

**Comment by josemmo** [comment]
Hola @jboscosimj,

Por ahora no, aunque es bastante probable que se añada en un futuro.

**Comment by jboscosimj** [comment]
Muy buenas @josemmo, te adjunto el código por si lo necesitas, lo he modificado de una version del Facturae-PHP que me descarge hace tiempo, lo digo por si ya ha cambiado tu código fuente.

Espero que te sirva.



[src.zip](https://github.com/josemmo/Facturae-PHP/files/2599699/src.zip)
