### ISSUE TITLE
Código SWIFT

### ISSUE THREAD

**Issue by txusms** [josemmo/Facturae-PHP#37]
Hola José Miguel,

Enhorabuena por el proyecto. Algunas entidades solicitan que se indique el código SWIFT o BIC junto al IBAN. ¿Está previsto incluirlo? Si lo prefieres, envío PR y lo valoras.

Gracias y Feliz Año Nuevo!

**Comment by josemmo** [comment]
Hola @txusms,

Me parece muy buena idea. El PR parece estar bien, mañana lo echo un vistazo y lo paso a `develop`.

Feliz año!

**Comment by txusms** [comment]
Genial @josemmo! Ya he visto el merge. 

Saludos!
