### ISSUE TITLE
Class FacturaeExportable not found

### ISSUE THREAD

**Issue by tomascrespo** [josemmo/Facturae-PHP#41]
Hola Jose, estoy intentando usar tu código para subir una factura, pero al ejecutar el ejemplo de envío de factura me dice 
`PHP Fatal error:  Class 'josemmo\Facturae\Controller\FacturaeExportable' not found in /var/www/facturae/Facturae-PHP/src/Facturae.php on line 9`

Lo uso sin composer, simplemente clonando el git.

Y pongo los requiere

```
require_once 'Facturae-PHP/src/Facturae.php';
require_once 'Facturae-PHP/src/FacturaeCentre.php';
require_once 'Facturae-PHP/src/FacturaeItem.php';
require_once 'Facturae-PHP/src/FacturaeParty.php';
require_once 'Facturae-PHP/src/FacturaExportable.php';

```

**Comment by tomascrespo** [comment]
Finalmente conseguí hacerlo funcionar incluyendo todos los require_once que me iba pidiendo en cada fichero php del src.

**Comment by josemmo** [comment]
De acuerdo, doy por cerrado el issue
