### ISSUE TITLE
Centro para Faceb2b

### ISSUE THREAD

**Issue by tomascrespo** [josemmo/Facturae-PHP#42]
Hola, estoy intentando generear una factura para subirla a Faceb2b. En la documentación pone que para modificar el ejemplo de factura simple y que sirva para Faceb2b se añade el centro así:
```
$b2b = $fac->getExtension('Fb2b');
$b2b->setReceiver(new FacturaeCentre([
  "code" => "51558103JES0001",
  "name" => "Centro administrativo receptor"
]));

```

Pero, ¿de dónde saco el código que remplaza a 51558103JES0001? ¿es el código DIRe del cliente al que quiero facturar? ¿o acaso ese valor es fijo porque es el centro receptor de Faceb2b?

Muchas gracias

**Comment by josemmo** [comment]
Hola @tomascrespo,

Ese código se corresponde con el ID del centro receptor (código DIRe). Haciendo un símil con el correo electrónico, sería algo así como la dirección del destinatario.
Te lo tiene que dar el receptor de la factura o puedes buscarlo en la página web https://dire.gob.es/.

**Comment by tomascrespo** [comment]
Perfecto, es el código DIRe del cliente entonces

**Comment by tomascrespo** [comment]
Ahora si consigo subir la factura sin problemas, pero al poco de subirla me mandan un email diciendo que ha sido rechazada porque:

000047: EFVAL09 - El departamento del receptor de la factura no existe

Supongo que eso tiene que ver con el centro administrativo que pongo. Simplemente he cogido el código DIRe de mi cliente, que está dado de alta en Faceb2b, de hecho es él quien me exige que le envíe la factura por Faceb2b

**Comment by josemmo** [comment]
Pues no te sabría decir, no parece que sea un fallo de Facturae-PHP si la factura se llega a subir.

Te recomiendo te pongas en contacto con el [equipo de soporte de FACeB2B](https://ssweb.seap.minhap.es/ayuda/consulta/FACEB2B) para resolver la duda.
