### ISSUE TITLE
MIME type no válido con FACeB2B

### ISSUE THREAD

**Issue by tomascrespo** [josemmo/Facturae-PHP#45]
Estoy intentando enviar una factura a Faceb2b. Toda la parte de generación y firma de la factura funciona correctamente, pero la parte del envío no. Pongo la parte del código relacionada:

```
// Ya solo queda firmar la factura ...
$fac->sign(
  "clave_publica.pem",
  "clave_privada.pem",
  "miclavesupersecreta"
);

// ... y exportarlo a un archivo
$fac->export("salida.xsig");


// Cargamos la factura en una instancia de FacturaeFile
$invoice = new FacturaeFile();
$invoice->loadData($fac->export(), "salida.xsig");

// Creamos una conexion con FACeb2b
$face = new Faceb2bClient("clave_publica.pem", "clave_privada.pem", "miclavesecreta");
$face->setProduction(false); // Descomenta esta linea para entorno de desarrollo

// Subimos la factura a FACe

//$res = $face->sendInvoice("compras@wondergrass.es", $invoice);
$res = $face->sendInvoice($invoice, $invoice);

echo "RESULTADO: " . $res->resultStatus->code . " \nMENSAJE: " . $res->resultStatus->message  . " \nDETALLE: " . $res->resultStatus->detail .  "\n";
//if ($res->resultado->codigo == 0) {
if ($res->resultStatus->code == 0) {
  // La factura ha sido aceptada
  echo "Numero de registro => " . $res->factura->numeroRegistro . "\n";
} else {
  // FACe ha rechazado la factura
//  echo "Factura rechazada " . $res->resultStatus->code . " " .$res->resultStatus->code . " " . $res->resultStatus->messaje . " " . $res->resultStatus->detail . " " ;
}

```
Y el resultado que obtengo al ejecutarlo:
```

RESULTADO: 0P001
MENSAJE: Parámetros de entrada inválidos
DETALLE: El parámetro mime de invoiceFile debe ser text/xml
El parámetro mime de attachmentFile debe ser application/zip

Numero de registro =>

```

Al parecer estoy haciendo algo mal a la hora de pasar los parámetros a sendInvoice, tanto la factura en sí como el adjunto, pero o sé qué

**Comment by tomascrespo** [comment]
De los dos errores, el del attchmentFile no me preocupa, pues supongo que el adjunto es opcional.
En cuanto al error del MIME Type de la factura, si hago:
`echo "MIME: ". $invoice->getMimeType()."\n";`
obtengo:
`MIME: application/xml`
¿Por qué la factura generada es application/xml y no text/xml?

**Comment by tomascrespo** [comment]
Si edito el código de FacturaeFile.php y fuerzo a que en mime ponga manualmente "text/xml"
Obtengo:
```
RESULTADO: AT001
MENSAJE: Error al autenticar el usuario
DETALLE: El certificado de firma SOAP no se encuentra o no estÃ¡ dado de alta
Numero de registro =>

```

Estoy dado de alta como cliente y como ESF, y he probado tanto con los dos archivos .pem separados del certificado como con el .pfx, ¿a qué se refiere "el certificado de firma SOAP"?

**Comment by josemmo** [comment]
Hola @tomascrespo,

Sobre el tema de la firma, estás trabajando en el entorno de staging al tener esta línea en tu código:
```php
$face->setProduction(false);
```
Si FACeB2B te devuelve el error AT001 es porque la clave con la que firmas las peticiones no está dada de alta en la plataforma de staging, puede ser que te hayas registrado solo en la de producción.

Por favor, abre otro issue si sigues teniendo problemas con ello para no mezclarlo con el tema inicial.

---

En cuanto al error 0P001, el MIME devuelto por Facturae-PHP para la factura es `application/xml` porque hasta ahora FACeB2B pedía ese tipo. Curiosamente, FACe pedía `text/xml`, parece que ya lo han normalizado.

Intentaré sacar un rato para corregirlo, si alguien quiere contribuir, ¡adelante! :+1:

**Comment by tomascrespo** [comment]
Muchas gracias @josemmo. Efectivamente si trabajo en modo producción no me da el error de autenticación. Miraré cómo darme de alta en el modo de pruebas también.

En cuanto al tipo MIME he editado la clase y le he puesto el tipo "text/xml" a la fuerza. 

Ahora si consigo subir la factura sin problemas, pero al poco de subirla me mandan un email diciendo que ha sido rechazada porque:

000047: EFVAL09 - El departamento del receptor de la factura no existe

Supongo que eso tiene que ver con el centro administrativo que pongo. Simplemente he cogido el código DIRe de mi cliente

**Comment by jarabito11** [comment]
Buenas tardes, me da un error al intentar enviar una factura a Face, el error es el siguiente:
![image](https://user-images.githubusercontent.com/33698838/62712672-9a68cc80-b9fb-11e9-827d-212236f29091.png)

No entiendo el error, ya que es de la clase. Mi código es el siguiente:

        $invoice = new FacturaeFile();
        $invoice->loadData($fac->export(), "salida.xsig"); //EL ERROR ES EN ESTA LINEA

        $faceb2b = new FaceB2bClient("clave_publica.pem", "clave_privada.pem", "javi");

        $faceb2b->setProduction(false);

        $res = $faceb2b->sendInvoice($invoice);
        if ($res->resultStatus->code == 0) {
            echo "Número de registro => " . $res->invoiceDetail->registryNumber . "\n";
        } else {
            echo "La facutra no ha sido aceptada.";
        }

**Comment by josemmo** [comment]
Hola @jarabito11,

¿Tienes la extensión FileInfo instalada y activada? Si estás usando Windows comprueba que el fichero `php.ini` tiene la línea `extension=php_fileinfo.dll` descomentada.

**Comment by jarabito11** [comment]
Hola @josemmo , ya lo he solucionado, era que usaba el comando php artisan serve para iniciarlo, y no tengo configurado ahi el php, he usado Xampp y me va perfecto.

Una pregunta, por casualidad no sabrás porque no me genera la Factura bien? Es decir, los totales de los productos y todo eso no los pone, me pone 1€.

Te dejo aqui la factura por si la quieres ver.

[fichero.txt](https://github.com/josemmo/Facturae-PHP/files/3489099/fichero.txt)

Un saludo :)

**Comment by josemmo** [comment]
Hola @jarabito11,

He modificado tu comentario anterior para retirar la factura adjunta que contenía información personal.

Si tienes dudas sobre el manejo de la librería [consulta la documentación](https://josemmo.github.io/Facturae-PHP/) o crea un issue nuevo.

**Comment by lualfer99** [comment]
@josemmo  como puedo darme de alta en el modo de pruebas también.?

**Comment by josemmo** [comment]
Hola @lualfer99,

Para usar FaceB2B en el entorno de pruebas sigue los pasos que aparecen en [este enlace](https://josemmo.github.io/Facturae-PHP/envio-y-recepcion/faceb2b.html) pero utiliza los servidores de staging en vez de los de producción:

- DIRe: https://se-dire.redsara.es
- FaceB2B: https://se-faceb2b.redsara.es
