### ISSUE TITLE
Formato de factura no válido

### ISSUE THREAD

**Issue by tomascrespo** [josemmo/Facturae-PHP#46]
Al generar una factura con la extensión Faceb2b y añadir la entidad pública y la referencia del contrato con:
```
$b2b->setPublicOrganismCode('E00003301');
$b2b->setContractReference('333000');

```
No consigo validadr el fichero .xsig generado. Los validadores me dan este error:

`Formato de factura no válido: (1): [Extensions] - (l2:c3400) - El comodín coincidente es estricto, pero no se ha encontrado ninguna declaración para el elemento 'fb2b`

**Comment by josemmo** [comment]
Hola @tomascrespo,

Que yo sepa ninguno de los validadores de FacturaE son capaces de validar documentos con extensiones, como es el caso con FACeB2B.

Aquí tienes un ejemplo con el [validador del Gobierno de España](https://sedeaplicaciones2.minetur.gob.es/FacturaE/index.jsp) advirtiendo de ello:

![](https://i.imgur.com/CiSZ4yv.png)

Doy por cerrado el issue.
