### ISSUE TITLE
Aplicar retención a una factura

### ISSUE THREAD

**Issue by VTCop** [josemmo/Facturae-PHP#49]
¿Cómo podría establecerse una retención en una factura?

Por ejemplo, en la factura:

```
    
<InvoiceTotals>
        <TotalGrossAmount>4.81</TotalGrossAmount>
        <TotalGeneralDiscounts>0.00</TotalGeneralDiscounts>
        <TotalGeneralSurcharges>0.00</TotalGeneralSurcharges>
        <TotalGrossAmountBeforeTaxes>4.81</TotalGrossAmountBeforeTaxes>
        <TotalTaxOutputs>1.01</TotalTaxOutputs>
        <TotalTaxesWithheld>0.00</TotalTaxesWithheld>
        <InvoiceTotal>5.82</InvoiceTotal>
        <TotalFinancialExpenses>0.00</TotalFinancialExpenses>
        <TotalOutstandingAmount>5.82</TotalOutstandingAmount>
        <TotalPaymentsOnAccount>0.00</TotalPaymentsOnAccount>
        <AmountsWithheld>
          <WithholdingReason>Garantía</WithholdingReason>
          <WithholdingAmount>2.50</WithholdingAmount>
        </AmountsWithheld>
        <TotalExecutableAmount>3.32</TotalExecutableAmount>
      </InvoiceTotals>

```

Los campos para la retención serían  <WithholdingReason> y <WithholdingAmount>
¿Alguno de los métodos de Facturae-PHP añade esos nodos al XML? ¿o existe algún modo de añadir esos nodos "a mano"?

**Comment by VTCop** [comment]
El pull request #50 permite poder añadir retenciones a la factura, usando el método addAmountWithheld()

**Comment by josemmo** [comment]
Hola @VTCop,

El PR que has propuesto hace fallar los [tests de Travis](https://travis-ci.org/josemmo/Facturae-PHP/builds/524609041). Además, no se si añadir 14 commits que se llaman igual a la rama `develop` es buena idea.

Si puede ser, mejor haz otro pull request.

**Comment by josemmo** [comment]
Cerrado por inactividad.

Para aquellos que estén buscando una forma de implementar modificaciones a una factura sin tener que alterar el código de la libraría se han creado las [extensiones de terceros](https://josemmo.github.io/Facturae-PHP/extensiones/#extensiones-de-terceros).
