### ISSUE TITLE
Aplicación impuestos en caso de descuento por linea de detalle

### ISSUE THREAD

**Issue by KaiserVito** [josemmo/Facturae-PHP#53]
Hola José,
parece que el calculo de la base imponible, y por consecuencia del IVA y del total de la factura, no tiene en cuenta eventuales descuentos que hemos aplicado a la linea individual.

Saludos

**Comment by josemmo** [comment]
Hola @KaiserVito,

¿Podrías pasar una factura de ejemplo indicando el problema?

**Comment by KaiserVito** [comment]
Hola José,
aquí la tienes.

Saludos, 

![item](https://user-images.githubusercontent.com/7655604/61202958-4fec7c80-a6e9-11e9-95c4-7b685d58f8c5.png)
![invoice](https://user-images.githubusercontent.com/7655604/61202959-4fec7c80-a6e9-11e9-82ea-2f4933ae66ef.png)
[Invoice_1_2019.xml.zip](https://github.com/josemmo/Facturae-PHP/files/3391376/Invoice_1_2019.xml.zip)

**Comment by josemmo** [comment]
Ya debería estar arreglado, las cuotas de los impuestos se estaban calculando a partir de la base imponible *antes* de aplicar descuentos y cargos.

@KaiserVito, prueba a volver a generar la factura desde la rama `develop` para confirmar que ya funciona correctamente.

**Comment by KaiserVito** [comment]
Hola José,
ahora si, todos los importes son calculados correctamente. Muchísimas gracias :-D

Saludos

**Comment by josemmo** [comment]
De acuerdo, doy por cerrado el issue.

Un saludo!
