### ISSUE TITLE
¿Los decimales en las facturas ya se validan correctamente?

### ISSUE THREAD

**Issue by PhoneixS** [josemmo/Facturae-PHP#56]
Estamos teniendo problemas con el redondeo de los decimales de los conceptos en las facturas y veo que tras el problema de #23 se optó por no dejar más decimales.

Pero creo que ya sí que se admiten más decimales; aunque creo que no en el total, sí que deja más decimales en Item/UnitPriceWithoutTax y Item/TotalAmountWithoutTax por lo menos. Al menos con el validador de https://se-face.redsara.es/es/facturas/validar-visualizar-facturas sí que las pasa como válidas.

¿Qué validador usas para comprobar el formato de las facturas?

En caso de que el sistema ya admitiera la cantidad de decimales que indican las especificaciones, habría que cambiar el array de las constantes de decimales para adecuarlas a las nuevas cantidades.

**Comment by PhoneixS** [comment]
También son admitidas en el entorno de pruebas al mandarlas automáticamente mediante la propia librería.

**Comment by josemmo** [comment]
Hola @PhoneixS,

> ¿Qué validador usas para comprobar el formato de las facturas?

El validador que utilizan los tests unitarios es https://viewer.facturadirecta.com, aunque el recomendado es el oficial del Gobierno de España (http://sedeaplicaciones2.minetur.gob.es/FacturaE/index.jsp), ya que hace más validaciones.

¿Podrías detallar cuál es el problema que estáis teniendo? Si los importes "tiemblan" es muy probable que se deba a #24.

**Comment by PhoneixS** [comment]
Sí, el problema es debido al redondeo de los decimales. Ya que según está implementado ahora no se pueden tener ciertos valores en el total final.

Por ejemplo el valor 671,00€ no se puede representar si se tiene un 21% de IVA. Ya que el valor total de la línea debería ser 554,54545455€ pero debido al redondeo de dos decimales debe ser 554.55€ del que se saca un iba del 116,4555€, redondeado a 116,46€; con lo que el total sería 671,01€. Y si se usa 554,54€ como base el resultado sería 554,54+116,45 = 670,99€.

¿Y si en vez de hacer el redondeo en cada parte según se van haciendo los cálculo se hiciera el redondeo solo al final en la exportación al xml? Así los cálculos serían lo más precisos posibles.

He probado con una factura con el precio unitario de 554,54545455€ y se valida correctamente en los dos portales y da el total correcto de 671,00€

Lo he implementado en la rama [PhoneixS/Facturae-PHP@patch-redondeo](https://github.com/PhoneixS/Facturae-PHP/tree/patch-redondeo), si quieres hago una nueva Pull request. He tenido que agregar el SCHEMA_3_2_1 ya que los decimales por defecto para `Item/GrossAmount` eran 2 a 8, pero deben ser 2 exactos.

**Comment by NeoRazorX** [comment]
Hola, disculpad que me meta.

El redondeo se debería realizar:
- Primero por línea (para evitar un número de decimales superior al que permite facturae, pero solamente en precio sin impuestos).
- Después se va acumulando totales por cada tipo de iva, sin redondear.
- Una vez se han recorrido todas las líneas, se redondean (con dos decimales) totales por cada tipo de iva.
- Por último se asigna la suma de los totales a la factura.

El redondeo es un tema peliagudo. Hay muchas implementaciones, pero al final manda Hacienda.

**Comment by PhoneixS** [comment]
¿Entonces, por así decirlo, una factura con el total de 671€ exactos sería ilegal ya que no hay forma de obtener ese valor?

**Comment by NeoRazorX** [comment]
Una factura de 671€ exactos (después del redondeo) se puede conseguir con una línea con cantidad 1, precio 554.546€ y 21% de IVA.

La base para el IVA 21% sería 554.546 que se redondea a 554.55. El IVA para el 21% sería 116,45466 que se redondea a 116,45. Y el total de la factura sería 671€.

**Comment by PhoneixS** [comment]
@NeoRazorX la base para el IVA ya tiene que estar redondeada, así que el cálculo del IVA se tendría que hacer con el 554.55, el cual da 116.45555 => 116.46.

**Comment by josemmo** [comment]
Como bien dice @NeoRazorX, el redondeo es un tema peliagudo. Facturae-PHP es una implementación del formato, y si el formato dice que hay que poner los totales con dos decimales, no queda otra que hacerlo así.

Me he fijado que [el validador del Gobierno](https://sedeaplicaciones2.minetur.gob.es/FacturaE/) tolera un céntimo de diferencia en los importes de los impuestos por línea, así que he añadido un corrector automático de importes solo para estos casos en el commit 24ad38dae88d9160e99b9dc9450f6b4774820585 (su test correspondiente es 3cc836b0297a1e1c6bc92fb4816b86d34c3575c8).

@PhoneixS, prueba a generar la factura que te da problemas con el código de la rama `develop` y nos cuentas, pero ten en cuenta que más no se va a poder hacer.

**Comment by NeoRazorX** [comment]
@PhoneixS No, la base del IVA no tiene que estar redondeada para calcular el IVA. Base e IVA se calculan y acumulan con todos los decimales, es solamente al final cuando se redondea. De lo contrario las diferencias son mayores.

**Comment by PhoneixS** [comment]
@josemmo Sí, con esos cambios las genera correctamente.
