### ISSUE TITLE
La librería no me genera el total de la factura.

### ISSUE THREAD

**Issue by jarabito11** [josemmo/Facturae-PHP#58]
Buenas, estoy intentando generar el total de la factura (importe bruto, etc) ya que no la genera el solo pero no se como. Me genera lo siguiente:

![img](https://user-images.githubusercontent.com/33698838/62825216-8adab680-bba8-11e9-98cd-6934e3e1ec94.jpg)

Aquí añado los items:
![image](https://user-images.githubusercontent.com/33698838/62825239-d55c3300-bba8-11e9-816e-bc7c3d57450b.png)

Supongo que será porque no me calcula los porcentajes del IVA.

**Comment by josemmo** [comment]
Hola @jarabito11,

No parece ser un fallo de la librería. Comprueba el valor de la variable `$request`.

**Comment by josemmo** [comment]
Cerrado por inactividad.
