### ISSUE TITLE
Versión de la extensión de faceb2b no encontrada o no soportada La unidad receptora no existe

### ISSUE THREAD

**Issue by jarabito11** [josemmo/Facturae-PHP#60]
Hola buenas tardes, tengo un problema a la hora de enviar la factura, alguien me puede ayudar?

Mi error es el siguiente: 
![image](https://user-images.githubusercontent.com/33698838/64444520-9c927980-d0d4-11e9-8777-f542bf0b6350.png)

El caso es que no se quien no está registrado, porque me he dado de alta en FaceB2B para poder enviar facturas desde el certificado de la empresa, pero no se, no entiendo bien este proceso. Lo más seguro es que sea de mi código. Esto estaría bien?

![image](https://user-images.githubusercontent.com/33698838/64444663-f004c780-d0d4-11e9-8c21-1900c0ec066a.png)

En "code" tengo que poner el NIF o DNI de cada una de las partes?

Agradecería un pequeño cable o una explicación de este proceso, muchas gracias de antemano, un saludo.
Javi.

**Comment by josemmo** [comment]
Hola @jarabito11,

La propiedad "code" de un `FacturaeCentre` tiene que ser un código [DIRe](https://dire.gob.es/) válido.

Por favor, consulta la documentación de la librería:

- [Extensión de FACeB2B](https://josemmo.github.io/Facturae-PHP/extensiones/faceb2b.html)
- [Comunicación con FACeB2B](https://josemmo.github.io/Facturae-PHP/envio-y-recepcion/faceb2b.html)
