### ISSUE TITLE
El formato de la factura es incorrecto

### ISSUE THREAD

**Issue by metelidrissi** [josemmo/Facturae-PHP#63]
![Screenshot_7](https://user-images.githubusercontent.com/3645641/101033791-8fd03000-357a-11eb-9912-ccdf0fd726fb.jpg)

Estoy realizando pruebas en el entorno de pruebas, el certificado digital que tenemos es válido y no está caducado, lo hemos subido al entorno de pruebas y al querer probar de generar una factura y enviar a Face (staging) nos salta este error:

`SimpleXMLElement Object ( [resultado] => SimpleXMLElement Object ( [codigo] => 408 [descripcion] => El formato de la factura es incorrecto [codigoSeguimiento] => 5fc8f2ce360d8 ) [factura] => SimpleXMLElement Object ( ) )`

En la imagen adjunta nos aparecen algunos campos conforme no son correctos, pero no sabemos que es lo que tenemos que hacer para que sea corregirlos.

¿Tenéis alguna idea?

Muchas gracias

**Comment by josemmo** [comment]
Hola @metelidrissi,

Según los resultados del validador, la factura generada por la librería parece cumplir con el formato FacturaE, el fallo tiene que estar en el certificado de firma.

Para que una factura sea admitida en FACe tiene que estar firmada con un certificado expedido por una entidad de certificación reconocida por el Gobierno de España (por ejemplo, por la FNMT).
¿Qué entidad ha expedido el certificado que os da problemas?

Un saludo,
José Miguel

**Comment by metelidrissi** [comment]
Hola @josemmo 

Gracias por tu respuesta. He estado estos días dándole vueltas, y he resuelto el punto.

El certificado realmente es correcto, y lo que no estaba bien como indicaba el error era el formato de la factura, los datos no coincidían con los de FACe. Una forma que vi de testearlo es generando la factura y luego subirla directamente a FACe en el entorno de pruebas, en el apartado **REMITIR FACTURAS.**

Ahí te va indicando lo que no tienes bien, esto quizá puede ayudar a alguien con el mismo caso.

Por otro lado, de tu documentación algo que me ayudó mucho es este ejemplo:

https://github.com/josemmo/Facturae-PHP/blob/master/doc/entidades/centros-administrativos.md

Ya que probé de usar exactamente los mismos datos y funcionó.

Un saludo José Miguel.

**Comment by josemmo** [comment]
Hola @metelidrissi,

Me alegro de que ya esté solucionado, doy el issue por cerrado.

Un saludo,
José Miguel
