### ISSUE TITLE
código DIR3 ?

### ISSUE THREAD

**Issue by jviure** [josemmo/Facturae-PHP#64]
Buenos dias, 
Por ahora va genial el plugin, pero al mandar una facturae a una administración pública me retornan esto:

![Imagen 3](https://user-images.githubusercontent.com/2384464/102468623-0dec0680-4052-11eb-88fc-f741cd8bef88.jpg)

Como se fija este código y cuando? gracias!

**Comment by josemmo** [comment]
Hola @jviure,

Los códigos DIR3 son necesarios para que FACe o el punto de entrada de facturas que uses sea capaz de hacer llegar la factura a su destinatario. En [este enlace de la documentación](https://josemmo.github.io/Facturae-PHP/entidades/centros-administrativos.html) tienes más información.

Un saludo,
José Miguel

**Comment by josemmo** [comment]
Cierro el issue por inactividad.
