### ISSUE TITLE
¿Se puede crear factura con cesión de crédito?

### ISSUE THREAD

**Issue by esorinas** [josemmo/Facturae-PHP#71]
Hola @josemmo,

Muchas gracias por esta libería tan útil y necesaria! 

Estoy intentando generar facturas con cesión de crédito, y me pregunto si hay alguna forma de hacerlo con este librería. Según las FAQs del FACe (https://lalin.gal/files/FACe%20Preguntas%20frecuentes%20Proveedores%201-2-3.pdf punto 2.8) esto es compatible con el FACe en versión 3.2.2 de Facturae.

Gracias!

**Comment by josemmo** [comment]
Hola, @esorinas!

Revisando la especificación de Facturae v3.2.2 veo que hay algunos campos en los que aparece la palabra "cesión" dentro del nodo `FactoryAssignmentData`. Supongo que te refieres a eso.

¿Podrías pasar un ejemplo de una factura con los campos que necesitas rellenar? Es la primera que oigo esto de la cesión de crédito... 😅

**Comment by esorinas** [comment]
Hola de nuevo @josemmo,

Estoy intentando conseguir una factura ejemplo para mostrártela (se la he pedido a la persona para la cual estoy desarrollando la funcionalidad), pero revisando el primer mensaje que te mandé creo que el link al documento es incorrecto. 

El documento que te quería remitir era este: (https://administracionelectronica.gob.es/ctt/resources/Soluciones/334/Descargas/FACe-FAQs-Proveedores.pdf?idIniciativa=334&idElemento=9452 punto 2.8 en adelante), por si acaso te lo adjunto también aquí
[FACe-FAQs-Proveedores.pdf](https://github.com/josemmo/Facturae-PHP/files/6181209/FACe-FAQs-Proveedores.pdf).

En ese documento comenta, como dices, que esa información va en el apartado FactoryAssignmentData. No sé si eso ayuda de algún modo. En cualquier caso cuando tenga una factura ejemplo te la hago llegar.

Muchas gracias!

**Comment by josemmo** [comment]
Hola @esorinas,

¿Hay alguna novedad sobre este issue?

Estoy pendiente de lanzar una nueva versión que soluciona un fallo importante con el validador del Gobierno de España y la firma electrónica. Si tienes ya el ejemplo puedo intentar meter la funcionalidad que pides en esa release.

**Comment by esorinas** [comment]
Hola @josemmo,

No he encontrado ninguna herramienta para crear una factura con cesión de crédito. Sin embargo, he encontrado una [documentación](https://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml) en una [página oficial del Gobierno](https://www.facturae.gob.es/formato/Paginas/version-3-2.aspx) que indica cuáles son los campos a añadir. A partir de esa documentación, he añadido manualmente unos campos al XML generado con esta librería (Ejemplo simple) para crear una factura con cesión de crédito. 

Sin embargo, siguiendo ese documento he añadido manualmente unos campos al XML generado a partir de la librería y el [visualizador de facturas del Gobierno](http://sedeaplicaciones2.minetur.gob.es/FacturaEVis/) entiende la factura y la desglosa correctamente. Te la adjunto bajo el nombre _Factura_con_cesion_3_2_2.xml_ dentro de una carpeta comprimida, ya que GitHub no me permite subir un archivo .xml.
![image](https://user-images.githubusercontent.com/43247096/114223623-56686080-9970-11eb-99d9-ed5692fc3478.png)


Esencialmente, he añadido el tag `<FactoringAssignmentData>` y, dentro de éste, los tags `<Assignee>` y `<PaymentDetails>`.

Dentro de `Assignee` he replicado los datos del vendedor (he copiado y pegado el contenido del tag `SellerParty`).
Dentro de `PaymentDetails` he replicado los datos del mismo tag `PaymentDetails` que genera la librería al usar el método `$fac->setPaymentMethod(Facturae::PAYMENT_TRANSFER, "ES7620770024003102575766");`

Espero que te sirva de algo este ejemplo. En cualquier caso, muchas gracias por tu labor y tu ayuda.

Un saludo,

[Factura_con_cesion_3_2_2.zip](https://github.com/josemmo/Facturae-PHP/files/6287773/Factura_con_cesion_3_2_2.zip)

**Comment by josemmo** [comment]
Hola @esorinas,

He mandado unos cambios a [develop](https://github.com/josemmo/Facturae-PHP/tree/develop) que incluyen la funcionalidad. Pruébalo y me dices si es lo que necesitas.

P.D.: cuidado con la factura de ejemplo que has adjuntado que no pasa el validador del Gobierno porque le falta el campo `FactoringAssignmentClauses`. El visualizador del Gobierno no valida las facturas.

**Comment by esorinas** [comment]
Buenos días @josemmo,

He probado la funcionalidad y todo genial, es lo que necesitaba. Por mi parte podemos cerrar este issue, y estaré atento a la nueva release para incorporarlo dentro de mi proyecto.

¡Un saludo y muchísimas gracias por tu tiempo y tu trabajo!

PD: ¿Tienes alguna aproximación de cuándo saldrá la versión? Sólo por preguntar, no hay problema si no hay fecha prevista.

**Comment by josemmo** [comment]
Hola, @esorinas!

Ya está publicada la nueva release: [v1.6.0](https://github.com/josemmo/Facturae-PHP/releases/tag/v1.6.0)
