### ISSUE TITLE
Pruebas en STAGING

### ISSUE THREAD

**Issue by VGordillo-Resulto** [josemmo/Facturae-PHP#74]
Hola @josemmo,

Estoy probando la librería con mi certificado registrado en FACe.

En PROD (https://webservice.face.gob.es/ facturasspp2) me funcionan correctamente las consultas, pero en STAGING (https://se-face-webservice.redsara.es/facturasspp2) siempre me devuelve el mismo error
```
[300] El certificado electrónico no está dado de alta en FACe. Para la presentación automatizada de facturas es necesario registrarse previamente en https://face.gob.es/es/proveedores
```

¿Hay que utilizar algún certificado distinto para las pruebas?

Muchas gracias.

**Comment by josemmo** [comment]
Hola @VGordillo-Resulto,

El entorno de staging está completamente aislado del de producción. Tienes que dar de alta el certificado de pruebas que tengas en https://se-face.redsara.es/es/proveedores/solicitud.

**Comment by VGordillo-Resulto** [comment]
¡¡¡Muchas gracias!!!

Llevaba horas buscando en documentación y no he encontrado nada que nos aclarase este tema.
