### ISSUE TITLE
Firmar FacturaeFile

### ISSUE THREAD

**Issue by VGordillo-Resulto** [josemmo/Facturae-PHP#75]
Hola @josemmo,

¿Se puede firmar una factura que el programa recoja de un fichero xml?

```
$fac = new Facturae();
// Importar factura desde fichero sin firmar
$invoice = new FacturaeFile();
$invoice->loadData($fac->export(), "test-invoice.xsig");
$face = new FaceClient("certificate.pfx", null, "pass");
$res = $face->sendInvoice("email@google.com", $invoice);
```

**Comment by josemmo** [comment]
La clase `FacturaeFile` sirve para representar [ficheros adjuntos](https://josemmo.github.io/Facturae-PHP/propiedades/datos-adicionales.html#documentos-adjuntos) dentro de una factura.

La funcionalidad de firma de un fichero XML cualquiera no está implementada, ya que lo habitual es generar y firma la factura con Facturae-PHP.

**Comment by josemmo** [comment]
Cerrado por inactividad.
