### ISSUE TITLE
Firmar factura con certificado nuevo

### ISSUE THREAD

**Issue by sandraescobedobadia** [josemmo/Facturae-PHP#76]
Hola,

he renovado el certificado hace poco y actualicé mi versión de Facturae-PHP a la 1.6.0 visto que había cambios en cuanto a los certificados. Sin embargo, desde entonce, FACe me devuelve el siguiente error:
{
       'codigo' =>  '428' 
       'descripcion' =>  'La firma de la factura es incorrecta'
       'codigoSeguimiento' =>  '609cd63302015'
}

¿Qué puede estar pasando?

Como información extra indicar que esto estaba funcionando con la versión 1.5.2 y el certificado anterior, hago uso de un archivo de certificado .p12 y su correspondiente contraseña y adjunto la factura firmada que obtengo y que envío.

¡Gracias de antemano!

**EDIT @josemmo**: Anonimizada factura
[mi-factura-redacted.zip](https://github.com/josemmo/Facturae-PHP/files/6473875/mi-factura-redacted.zip)

**Comment by josemmo** [comment]
Hola @sandraescobedobadia,

La factura que has subido parece una factura real, he modificado el post original para ocultar los datos del emisor y el receptor.

Al validar la factura con el [validador del Gobierno de España](https://sedeaplicaciones2.minetur.gob.es/FacturaE/) obtengo este error:
```
FacturaE 3.2.1,The prefix "xades" for element "xades:QualifyingProperties" is not bound.
```

Esto se debe a que falta declarar el namespace de "xades" en la raíz del documento o en el nodo `ds:Signature`:
```
xmlns:xades="http://uri.etsi.org/01903/v1.3.2#"
```

---

Dicho esto, no puedo arreglar el fallo que mencionas porque la factura que has subido no ha sido generada con Facturae-PHP. Esto se puede ver, por ejemplo, en los IDs de los nodos XAdES, ya que esta librería los nombra de otra forma.

Creo que la factura ha sido generada con la [aplicación de escritorio del Gobierno de España](https://www.facturae.gob.es/formato/Paginas/descarga-aplicacion-escritorio.aspx), si es así tienen un [teléfono de contacto](https://www.facturae.gob.es/Paginas/contacto.aspx) para incidencias como esta, aunque me parece que ya no dan soporte.

Un saludo,
José Miguel

**Comment by josemmo** [comment]
Cerrado por inactividad.
