### ISSUE TITLE
Error, cuando solicito totales en Facturae

### ISSUE THREAD

**Issue by fjsampe** [josemmo/Facturae-PHP#77]
Con estos datos, donde además de poner descuento en línea de detalle, indico un descuento general en la factura.
Observo que el iva lo calcula de la base en vez del total sin impuestos.

```
$fac = new Facturae();
    ...    
$fac->addItem(new FacturaeItem([
"name"=>"Linea 1"],
"quantity"=>1,
"unitPriceWithoutTax"=>580,
"discounts"=>[
                    ["reason"=>"Descuento linea","rate"=>10]
                ],
                "taxes"=>[
                    Facturae::TAX_IVA => 10
                ]
            ]));
        
  $fac->addDiscount('Dto.sobre base imponible total',20);
  $totales=$fac->getTotals();

```

![image](https://user-images.githubusercontent.com/18520482/123668387-570be700-d83b-11eb-9046-3ae8b8825dc8.png)

Como se observa el iva  no se calcula del total sin impuestos sino de la base. 

Gracias anticipadas

**Comment by fjsampe** [comment]
Lo he solucionado indicando el descuento de cada línea como la suma del descuento de linea + descuento de factura, pero quisiera consultar si se puede indicar los descuentos por separado y que calcule adecuadamente.

Gracias anticipadas

**Comment by josemmo** [comment]
Hola @fjsampe,

Si no lo he entendido mal, el problema está en que el IVA 10% de la factura se está calculando sobre una base imponible de 522,00 € en vez de sobre 417,60 €. ¿Es eso?

**Comment by fjsampe** [comment]
Correcto. Debería de calcularse del total sin impuestos.

**Comment by josemmo** [comment]
Por cómo está planteada la [especificación de FacturaE](https://www.facturae.gob.es/formato/Versiones/Esquema_castellano_v3_2_x_06_06_2017_unificado.pdf) ahora mismo no se me ocurre ninguna forma de ajustar la base imponible de los totales de impuestos de una factura. Me explico:

En caso de una línea de producto, añadir un descuento/cargo implica ajustar el importe bruto de esa línea y luego calcular el importe de cada impuesto en base al dato anterior. Por ejemplo:
```
Base imponible:    100,00 €
Descuento del 20%: -20,00 €
___________________________
Importe bruto:      80,00 €
IVA al 10%:        +88,00 €
___________________________
Total de la línea: 168,00 €
```

Ahora bien, una factura puede tener líneas de productos con impuestos diferentes (ej. una línea con IVA 10% y otra con IVA 21%), y esto plantea un problema.

Vamos con los descuentos/cargos aplicables a la factura en vez de a una línea. Supongamos que queremos aplicar un descuento global del 15% a una factura como esta:
```
========= LÍNEA 1 =========
Base imponible:    100,00 €
Importe bruto:     100,00 €
IVA al 10%:        +10,00 €
___________________________
Total de la línea: 110,00 €

========= LÍNEA 2 =========
Base imponible:    100,00 €
Importe bruto:     100,00 €
IVA al 21%:        +21,00 €
___________________________
Total de la línea: 121,00 €

========= FACTURA =========
Importe bruto:     200,00 €
Descuento del 15%: -30,00 €
Total IVA al 10%:  ???,?? €
Total IVA al 21%:  ???,?? €
```

Como los descuentos/cargos totales no se asocian a ningún impuesto (así lo dice la especificación) no se me ocurre ninguna forma de recalcular la base imponible de cada impuesto.

Entiendo que esto seguramente no sea la respuesta ideal pero aún así creo que es importante explicar por qué ocurre esto.

Un saludo,
José Miguel

**Comment by fjsampe** [comment]
Muchas gracias por la aclaración.
