### ISSUE TITLE
Error al exportar una factura con FACTURAE

### ISSUE THREAD

**Issue by zapa-gentoo** [josemmo/Facturae-PHP#78]
Hola.

Obtengo el siguiente error al intentar realizar una exportación de una factura:

Fatal error: Call to a member function getXML() on null in /var/www/localhost/htdocs/facturacion/lib/Facturae-PHP-master/src/FacturaeTraits/ExportableTrait.php on line 90

**Comment by josemmo** [comment]
Hola @zapa-gentoo,

Por la línea donde ocurre el error lo más seguro es que no hayas especificado los datos del comprador en la factura:
https://github.com/josemmo/Facturae-PHP/blob/c0d903929de2d6859c01c9e62f764739726a8a7d/src/FacturaeTraits/ExportableTrait.php#L86-L92

En [este enlace](https://josemmo.github.io/Facturae-PHP/ejemplos/factura-simple.html) tienes un ejemplo de cómo crear una factura con Facturae-PHP.

**Comment by josemmo** [comment]
Cerrado por falta de actividad.
