### ISSUE TITLE
X509IssuerName error oid 2.5.4.97

### ISSUE THREAD

**Issue by PaolaRuby** [josemmo/Facturae-PHP#82]
**organizationIdentifie**r **2.5.4.97** no se muestra correctamente , al validar con java el xml sale
```
SEVERE: El formato del nombre de Issuer de un certificado de SigningCertificate no se ajusta a X500: 
improperly specified input name: 
UNDEF=VATES-A66721499,CN=UANATACA CA2 2016,OU=TSP-UANATACA,O=UANATACA S.A.,L=Barcelona,C=ES
```

En `X509IssuerName` sale **`UNDEF=`**
`UNDEF=VATES-A66721499,CN=UANATACA CA2 2016,OU=TSP-UANATACA,O=UANATACA S.A.,L=Barcelona,C=ES` 
pero deberia ser algo asi
`OID.2.5.4.97=VATES-A66721499,CN=UANATACA CA1 2016,OU=TSP-UANATACA,O=UANATACA S.A.,L=Barcelona,C=ES`
`2.5.4.97=VATES-A66721499,CN=UANATACA CA1 2016,OU=TSP-UANATACA,O=UANATACA S.A.,L=Barcelona,C=ES`

**Ejemplos de 2.5.4.97:**
https://github.com/luisgoncalves/xades4j/blob/855738c009524a721b4e29f1c22dc27ce6a730d5/src/test/java/xades4j/verification/Issue166Test.java#L19-L21

https://github.com/josemmo/Facturae-PHP/blob/3f4885d9e5b69c98491995742d43fceaaafd81fc/src/FacturaeTraits/SignableTrait.php#L90-L94

Parece un problema de `openssl_x509_parse`, no es lo ideal, pero talvez corregirlo así por el momento
```php
 $certIssuer = []; 
 foreach ($certData['issuer'] as $item=>$value) { 
   if($item=='UNDEF'){
      if($value=='VATES-A66721499') $item='OID.2.5.4.97';
      else if(in_array($value,['#0c0f56415445532d413636373231343939','#130f56415445532d413636373231343939'])) $item='2.5.4.97';
   }
   $certIssuer[] = "$item=$value"; 
 } 
 $certIssuer = implode(',', array_reverse($certIssuer)); 
```

**Comment by josemmo** [comment]
Hola @PaolaRuby,

¿Podrías pasar un certificado de prueba (que no esté expedido de verdad por una CA) para poder reproducir el fallo?

He probado a parsear los metadatos del ejemplo [PFnubeAFEmpresa.crt](https://web.uanataca.com/common/project/pdf/autoridad-certificacion/pf.zip) con "openssl_x509_parse" y PHP le da correctamente el nombre "organizationIdentifier" al campo "2.5.4.97".

**Comment by PaolaRuby** [comment]
No tengo un certificado de prueba, solo los privados de terceros, si te funciona correctamente el 2.5.4.97 en el issuer talvez necesito actualizar la librería, por el momento pase el problema con el if, intentaré llevar las librerias a la más actual para ver si se soluciona

Gracias por la pronta respuesta

**Comment by PaolaRuby** [comment]
**UPDATE:** 
Tambien sale `organizationIdentifier=`, entonces actualice el `if` acorde los problemas q han surgido

```php
if(in_array(strtoupper((string) $item),['', 'OID','UNDEF','ORGANIZATIONIDENTIFIER'])){ // Arreglo para firmas UANATACA
```

Espero le pueda ser util a alguien
