### ISSUE TITLE
Politica de firma de Facturae

### ISSUE THREAD

**Issue by agorer** [josemmo/Facturae-PHP#83]
Hola,
     veo en el documento de la política de firma de facturae (https://www.facturae.gob.es/politica_de_firma_formato_facturae/politica_de_firma_formato_facturae_v3_1.pdf) que en el caso de usar el formato avanzado con evidencias ante terceros se tiene que usar el perfil XADES-X-L que incorpora el timestamp e información sobre los certificados y su estado de revocación.

En Facturae-PHP solo veo implementado la parte del timestamp, ¿es por quá a nivel practico no es necesaria la parte de información sobre los certificados en la generación de facturas de este tipo?

**Comment by josemmo** [comment]
Hola @agorer,

Hasta ahora nunca he visto un documento de FacturaE firmado en XAdES-X-L, lo máximo XAdES-T, y muchos puntos de entrada ni siquiera admiten sellado de tiempo (por ejemplo, FACe).

Así que el principal motivo por el que no está implementado en la librería es porque nadie lo había pedido antes.

Se podría implementar, pero salvo que sea un requisito de alguna administración no se si merece la pena el esfuerzo técnico.

**Comment by agorer** [comment]
Gracias por la respuesta, supongo que es una de esas cosas que pese a estar en el estandar nunca llegan a la implementación.
