### ISSUE TITLE
MIME no válido FACe

### ISSUE THREAD

**Issue by bprietonogal** [josemmo/Facturae-PHP#84]
Buenas,

     Tal y como se especificó en el issue #45, en Faceb2bClient está especificado que el MIME de la factura sea text/xml, y así me ha estado funcionando todo este tiempo. 
     
     Sin embargo, ayer me empezaron a fallar los envíos de las facturas. Recibo error 311 - El MIME de la factura es incorrecto. Actualmente no tengo acceso al código que firma y envía la factura, solo a la generación del xml que se envía para firmar, y antes de poder solicitar que cambien esa línea por "application/xml", quería preguntar si os está pasando también, o si es algún otro error que no esté encontrando con un texto que no corresponde. 

     En la documentación de FACe, en el uso del servicio web para enviar, aparece en los ejemplos "application/xml", aunque es verdad que es un manual de 2019 y hasta ahora me había funcionado text/xml. ¿Sabéis si se ha cambiado algo? Gracias!

**Comment by josemmo** [comment]
Hola @bprietonogal,

No parece que haya cambiado nada en el webservice de FaceB2B ya que [los tests](https://github.com/josemmo/Facturae-PHP/blob/3f4885d9e5b69c98491995742d43fceaaafd81fc/tests/WebservicesTest.php#L113) siguen pasando a fecha de hoy.

¿Podrías pasar un ejemplo de código para poder reproducir el fallo?

**Comment by bprietonogal** [comment]
He probado a reenviar una factura que fue enviada hace un mes (esperando que, si no hay cambios en FACe ni cambios en el código, la factura debería enviarse y recibir un error indicando que la factura ha sido ya enviada), y recibo el mismo error, que el MIME es incorrecto. No se ha cambiado nada del código que realiza la firma y el envío en este tiempo.

Básicamente, yo genero el xml antes de firmarlo, cuyo formato es válido según los dos validadores ([éste](http://sedeaplicaciones2.minetur.gob.es/FacturaE/ValidarCompleto) y [éste](https://face.gob.es/es/facturas/validar-visualizar-facturas)), y por cURL lo envío, junto con el email que recibirá las notificaciones, al servidor donde está la firma y al que no tengo acceso. El código que lo firma recoge ambos campos, y hace: 

```
    $factura=new Facturae();
    $factura->sign($ficheroPFX, null, $clavePFX);
    $xmlFirmado=$factura->injectSignature($xml);
    
    $face = new FaceClient($ficheroPFX, null, $clavePFX);
    
    $invoice = new FacturaeFile();
    $invoice->loadData($xmlFirmado, "invoice.xsig");
    $res = $face->sendInvoice($emailEnvio, $invoice);
    print $res->asXML();
```
No se ha modificado ni la clase FacturaeFile ni FaceClient ni Facturae. 

Estoy tratando de hacer pruebas, pero como no tengo acceso a la firma, no puedo registrarla en el entorno staging. ¿No existe algún fichero válido de firma para poder realizar pruebas?

**Comment by josemmo** [comment]
Puedes descagar certificados eIDAS válidos para pruebas desde la web del [DNI Electrónico](https://www.dnielectronico.es/portaldnie/PRF1_Cons02.action?pag=REF_1116&id_menu=68).

El código de envío parece estar bien pero el de generación de la factura es incorrecto:
```php
$factura = new Facturae();
// Aquí falta añadir los datos del emisor, receptor y líneas de producto
$factura->sign($ficheroPFX, null, $clavePFX);
$xmlFirmado = $factura->injectSignature($xml); // Este método es interno y no devuelve la factura firmada, solo la firma
```

En [este enlace](https://josemmo.github.io/Facturae-PHP/ejemplos/factura-simple.html) tienes un ejemplo de generación de una factura con Facturae-PHP y en [este otro](https://josemmo.github.io/Facturae-PHP/ejemplos/envio-face.html) un ejemplo de cómo mandar la factura generada a FACe.

Tampoco me queda claro si el fallo ocurre con FACe (como aparece en el código) o con FACeB2B (como pone en el título del issue).

**Comment by bprietonogal** [comment]
Vale, por partes... Primero, tienes razón, es FACe, no FACeB2B. Y es FACe el que estamos utilizando. Cambio el título del issue, perdón.

La generación de la factura no la he puesto, creo que no me expliqué bien. Yo genero la factura, y guardo en una variable todo el xml de la factura (y si lo imprimo en un fichero o por pantalla y copio a fichero xml, y lo paso por los validadores, el xml de la factura está bien formado). Hasta ahí todo perfecto.

El resto lo tengo como en el ejemplo que pones, usé el manual para basarme en todo lo que he hecho, e incluso si quiero solo firmarlo y no enviarlo, consigo el fichero completo sin problemas firmado. El problema me viene al enviarlo, que me dice que el MIME no es válido. El MIME que me sale en el fichero firmado es text/xml. 

Ahora mismo los certificados que tenía de prueba me dan error, pero en cuanto me descargue los que hay en la página del dni electrónico probaré todo de nuevo y a ver si consigo reproducir el error en pruebas, o si puedo cambiar el MIME y que funcione. Ya os contaré. Muchas gracias!

**Comment by bprietonogal** [comment]
Buenas,

Bueno, pues parece que hemos encontrado la causa. Por alguna razón, cuando firmábamos anteriormente, si poníamos la declaración del xml en la cadena que firmábamos, nos daba un error, así que enviábamos la factura sin ella, y se la tragaba sin problemas. Pero han debido de cambiar algo, porque ahora sí necesita que se envíe la declaración obligatoriamente. Limpiando todos los saltos de línea y añadiendo la cabecera antes de firmar, nos ha dejado enviar sin problemas. Así que aunque el error que nos daba era todo el tiempo MIME inválido, no se refería al MIME especificado dentro del xml sino que no se indicaba en la cabecera que era un xml. 
Cierro. Muchas gracias!
