### ISSUE TITLE
Factura sin IVA pero con IRPF

### ISSUE THREAD

**Issue by NeoRazorX** [josemmo/Facturae-PHP#88]
Me he encontrado el caso de que si crear una factura con IRPF pero sin IVA, el validador de facturae devuelve el error:

FacturaE 3.2.1,cvc-complex-type.2.4.a: Invalid content was found starting with element 'TaxesWithheld'. One of '{TaxesOutputs}' is expected.

Entiendo que primero espera encontrar un TaxesOutputs, es decir, un impuesto, y luego una retención. Como no encuentra TaxesOutputs, lanza el error.

¿Cómo estoy generando la factura?
- Para cada línea de la factura, si tiene IVA le estoy asignando el taxes[Facturae::TAX_IVA] = $linea->iva
- Para cada línea de la factura, si tiene IRPF le estoy asignando el taxes[Facturae::TAX_IRPF] = $linea->irpf

Es decir, si la línea no tiene IVA, no estoy asignando taxes[Facturae::TAX_IVA] ¿debería ponerlo a cero? He buscado un poco de información sobre este caso pero no he encontrado nada.

**Comment by josemmo** [comment]
Hola @NeoRazorX,

Depende de la factura que estés generando. Aquí ya tienes que preguntar a la Administración Pública a la que tengas que emitir la factura.

Por normal general, yo lo que he visto hacer son facturas con IVA 0% a las que se añade un [texto literal](https://josemmo.github.io/Facturae-PHP/propiedades/textos-literales.html) justificando el motivo.
