### ISSUE TITLE
How can I generate certificate to sign invoice?

### ISSUE THREAD

**Issue by scramatte** [josemmo/Facturae-PHP#9]
Hello,

How can I generate certificate to sign invoice?
Regards

**Comment by josemmo** [comment]
Hi!

Facturae-PHP cannot generate digital certificates as they need to be issued by a Certificate Authority, which in this case is the [FNMT](http://www.fnmt.es/) or any other Spanish goverment agency.

If you already have a valid certificate in PFX format but don't how to extract both public and private keys from it, try using OpenSSL:

```
openssl pkcs12 -in input_certificate.pfx -clcerts -nokeys -out public_key.pem
openssl pkcs12 -in input_certificate.pfx -nocerts -out private_key.pem
```

Once you do that, you can then use the resulting files in Facturae-PHP:

```php
$fac->sign(
    "ruta/hacia/clave_publica.pem",
    "ruta/hacia/clave_privada.pem",
    "the_passphrase_you_entered_before_when_creating_private_key"
);
```
