### ISSUE TITLE
Problema con descuentos de cabecera

### ISSUE THREAD

**Issue by MonicaWolf** [josemmo/Facturae-PHP#91]
Buenos días, 
El calculo de los impuestos en facturas que llevan descuentos de cabecera no lo esta haciendo correctamente. Parece que no tienen en cuenta la base imponible menos los descuentos de cabecera antes de hacer el calculo de las cantidades de los impuestos.

![image](https://user-images.githubusercontent.com/105430067/168064508-3d162859-ef82-4625-940a-392479af2b72.png)

Un saludo,

**Comment by josemmo** [comment]
Hola @MonicaWolf,

¿Podrías subir una factura de ejemplo en XML en la que ocurra el fallo? ¿Cuáles son los valores correctos que deberían aparecen?

**Comment by MonicaWolf** [comment]
Buenos días,
adjunto ejemplo de factura. El problema esta en el calculo del IVA, que lo hace sobre el importe bruto,  y no sobre el importe bruto antes de impuestos ( cuando ya se han aplicado los descuentos de cabecera).

[Factura_2022-000001 (22).zip](https://github.com/josemmo/Facturae-PHP/files/8699267/Factura_2022-000001.22.zip)

En este ejemplo, los cálculos del IVA correctos serían:

Iva:
64,80 * 0,21= 13,61
36*0,1 = 3,60

RE
64,80*5,2=3,37
36*1,4=0,50
Un saludo,

**Comment by MonicaWolf** [comment]
Hola,
he estado revisando los datos de la factura y no entiendo por que metes el recargo. La factura lleva dos descuentos de cabecera, uno del 10% y luego un descuento pronto pago.
Esta factura no lleva recargo. En la que tu me has puesto, sobraría la parte del recargo, supongo que con eso saldría bien.
Viendo los cálculos del IVA, el primero esta correcto. El segundo no, la base imponible sobre la que se calcula es 36.
Te pongo una captura de pantalla de mi programa de facturacion donde se ven los calculos y cantidades que deben salir en la factura que te indique:

![image](https://user-images.githubusercontent.com/105430067/169498355-987a68de-c712-4da6-ab06-e28a2c0c8bc7.png)

Muchas gracias!!!

**Comment by josemmo** [comment]
Vamos a hacer una cosa, porque si no, esto no avanza. Este el código que (creo) define la factura que aparece en la captura de pantalla:

```php
use josemmo\Facturae\Facturae;
use josemmo\Facturae\FacturaeItem;
use josemmo\Facturae\FacturaeParty;

$fac = new Facturae();
$fac->setNumber('FAC2022', '0001');
$fac->setIssueDate('2022-05-20');
$fac->setSeller(new FacturaeParty([
    'taxNumber' => 'A00000000',
    'name'      => 'Perico de los Palotes S.A.',
    'address'   => 'C/ Falsa, 123',
    'postCode'  => '12345',
    'town'      => 'Madrid',
    'province'  => 'Madrid'
]));
$fac->setBuyer(new FacturaeParty([
    'isLegalEntity' => false,
    'taxNumber'     => '00000000A',
    'name'          => 'Antonio',
    'firstSurname'  => 'García',
    'lastSurname'   => 'Pérez',
    'address'       => 'Avda. Mayor, 7',
    'postCode'      => '54321',
    'town'          => 'Madrid',
    'province'      => 'Madrid'
]));
$fac->addItem(new FacturaeItem([
    'name' => 'Prueba producto',
    'unitPriceWithoutTax' => 90,
    'taxes' => [
        Facturae::TAX_IVA => ['rate'=>21, 'surcharge'=>5.2]
    ]
]));
$fac->addItem(new FacturaeItem([
    'name' => 'Prueba 2',
    'unitPriceWithoutTax' => 50,
    'taxes' => [
        Facturae::TAX_IVA => ['rate'=>10, 'surcharge'=>1.4]
    ]
]));
$fac->addDiscount('Dto. cabecera', 10);
$fac->addDiscount('Dto. pronto pago', 25.20, false);

echo $fac->export();
```

¿Podrías probar a generar esta factura con la última versión de la libraría (develop)?

```
composer require josemmo/facturae-php:dev-develop
```

Una vez lo tengas, por favor, indícame qué campos se están generando de forma incorrecta y por qué.

**Comment by josemmo** [comment]
Hola @MonicaWolf,

Creo que (ahora sí) ya está arreglado el cálculo de los impuestos totales. Por favor, échale un vistazo a esta factura para confirmar que está todo correcto y poder sacar una actualización de la librería:
https://gist.github.com/josemmo/96df09b82cc7cbf4971dcdb71cae65df

La factura la he generado con el código que pasé en el mensaje anterior. Tal y como hablamos lleva:
- Un descuento global del 10%
- Un descuento global de 25,20 €
