### ISSUE TITLE
Propiedad LineItemPeriod no puede ser añadida

### ISSUE THREAD

**Issue by danider96** [josemmo/Facturae-PHP#92]
Hola, 

Estoy tratando de añadir la propiedad "LineItemPeriod" dentro del Item con sus propiedades "StartDate" y "EndDate", he probado a ha añadirlo de diferentes maneras pero no he podido y no he encontrado en la documentación la forma de meterlo.

He visto que la propiedad esta en los schemas.

Ejemplo: 

$fac->addItem(new FacturaeItem([
  "description" => "Una descripción de hasta 2500 caracteres",
  "articleCode" => 1234,          // Código de artículo
  "fileReference" => "000298172", // Referencia del expediente
  "fileDate" => "2010-03-10",     // Fecha del expediente
  "sequenceNumber" => "1.0",      // Número de secuencia o línea del pedido

  "LineItemPeriod" => [
                     "StartDate" => "2010-03-10",
                      "EndDate" => "2011-03-10"
]
]));

No se si hay alguna otra forma de añadirlo.

Gracias.

**Comment by josemmo** [comment]
Hola @danider96,

La funcionalidad que mencionas no está implementada en Facturae-PHP.
Lo apunto para la próxima release.
