### ISSUE TITLE
¿Sería posible adaptar Facturae-php para el envio de facturas facturae a un web service alojado en bizkaia?

### ISSUE THREAD

**Issue by asierblaz** [josemmo/Facturae-PHP#99]
¿Sería posible adaptar Facturae-php para el envio de facturas facturae a un web service alojado en bizkaia?

https://test-fakturpro.biscaytik.eus/efaktur/empresas/ayuda.action

Utiliza una estructura similar a la peticion soap del webservice del gobierno.

un saludo.

**Comment by josemmo** [comment]
Hola @asierblaz,

Si el punto de entrada es compatible con el WSDL de FACe, Facturae-PHP ya lo implementa a través del cliente personalizado. En [este enlace](https://josemmo.github.io/Facturae-PHP/envio-y-recepcion/face.html#cliente-personalizado) tienes la documentación.
